carpenstreet/blender

release/scripts/startup/abler/custom_properties.py

https://github.com/ACON3D/blender-deprecated/pull/23
저번 레포에서 PR로 넣은게 레포 옮기면서 누락된거 같습니다!

Sun Properties step 추가

---

release/scripts/startup/abler/object_control.py

센트리 오류로 나온 내용입니다. 카드 참조 부탁드립니다.
https://www.notion.so/acon3d/NoneType-object-has-no-attribute-ACON_prop-49c4dd96a712421b8bc81b1bc2a83b51

classmethod로 NoneType 패스하기

---

release/scripts/startup/abler/camera_control.py

3.0 버전에 같은 PR 올립니다.
(https://github.com/ACON3D/ABLER/pull/125)

cameraName이 없을 때 에러

---

release/scripts/startup/abler/object_control.py

GroupNavigation에도 NoneType 에러가 발생해 추가해주었습니다.
(노션카드 : https://www.notion.so/acon3d/GroupNavi-NoneType-798db4eb1d29466ea552bac9b8cc6666)

GroupNavigationPanel에 @classmethod 추가

---

.gitignore
launcher_abler/AblerLauncher.py

런쳐 이상한 코드 살짝만 리팩토링

---

launcher_abler/AblerLauncher.py

Check launcher 함수에서 혹시 바라보고 있는 repo의 release가 없으면 not found라는 json을 반환해서 오류로 잡히지 않았고, 그래서 의도대로 작동하지 않았던 문제를 해결했습니다.
req의 message가 Not Found일 경우 Run Abler를 표출하는 UI를 보이도록 설정했습니다!

checking if request has real response

---

release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/lib/tracker/_tracker.py

세부 내용
- 로그인 실패 원인별 Exception 클래스를 구분
- 사용자 책임이 아닌 예외가 발생했을 때 Sentry 에 에러리포팅 추가

로그인 실패 원인을 자세히 알 수 있도록 에러리포팅 개선

---

release/scripts/startup/abler/lib/tracker/_mixpanel.py

이 PR은 이전 에이블러 저장소의 아래 PR 에서 리뷰됐던 내용으로, 3.0 기반 에이블러에 해당 내용을 옮겨오는 PR 입니다.
https://github.com/ACON3D/ABLER/pull/126

(0.1.9 수정사항) 믹스패널 트래킹 부분에서 반복적으로 발생하고 있는 에러에 대한 처리 추가

---

release/scripts/startup/abler/custom_properties.py

코니방 변경해주면서 태양 강도가 1.0으로 들어가있어 startup.blend에서 1.5로 변경해주었습니당

코니방 태양 강도 변경

---

launcher_abler/AblerLauncher.py

Dispatch가 필요가 없는데 버그를 발생시키는 런쳐에서의 문제가 있어서 해당 부분 삭제했습니다.

dispatch bugfix

---

build_files/buildbot/README.md
build_files/buildbot/buildbot_utils.py
build_files/buildbot/codesign/absolute_and_relative_filename.py
build_files/buildbot/codesign/archive_with_indicator.py
build_files/buildbot/codesign/base_code_signer.py
build_files/buildbot/codesign/config_builder.py
build_files/buildbot/codesign/config_common.py
build_files/buildbot/codesign/config_server_template.py
build_files/buildbot/codesign/linux_code_signer.py
build_files/buildbot/codesign/macos_code_signer.py
build_files/buildbot/codesign/simple_code_signer.py
build_files/buildbot/codesign/util.py
build_files/buildbot/codesign/windows_code_signer.py
build_files/buildbot/codesign_server_linux.py
build_files/buildbot/codesign_server_macos.py
build_files/buildbot/codesign_server_windows.bat
build_files/buildbot/codesign_server_windows.py
build_files/buildbot/config/blender_linux.cmake
build_files/buildbot/worker_bundle_dmg.py
build_files/buildbot/worker_codesign.cmake
build_files/buildbot/worker_codesign.py
build_files/buildbot/worker_compile.py
build_files/buildbot/worker_pack.py
build_files/buildbot/worker_test.py
build_files/buildbot/worker_update.py

메인 브랜치에 다른 부분에서는 영향 안미치는 스크립트 추가해봅니당

메인 브랜치에 buildbot  스크립트 추가해서 테스트

---

build_files/buildbot/worker_compile.py

This repository is only used as a mirror of git.blender.org. Blender development happens on
https://developer.blender.org.
To get started with contributing code, please see:
https://wiki.blender.org/wiki/Process/Contributing_Code

ci-optix off

---

.github/workflows/ABLER-ci.yml
build_files/buildbot/worker_compile.py

1차적으로 CI 세팅을 완료했습니다.
이거 테스트하는 겸해서 강제로 푸시 넣겠습니다~!!!

PR 생성 혹은 ABLER/main 브랜치로 Push가 발생할 경우에 자동으로 빌드해서 bin/Release 압축해서 업로드

---

.github/workflows/ABLER-ci.yml

Archive 지우기 추가

---

release/scripts/startup/abler/credential_modal.py

팝업 메세지 추가해주었습니다.
(+ 437~440 line에선 자동로그인 시 modal의 invoke가 실행안되고 있어서 조건문을 없애주었습니다.)
locale의 번역도 push 해주었습니다.

0.2.1버전 팝업 메세지 추가

---

.github/workflows/ABLER-ci.yml
release/scripts/startup/abler/pref.py

에이블러를 켤 때 (file load handler가 실행될 때) 키맵이 "ABLER"로 되어있는지 확인하고 아닌 경우 세팅을 바로 잡아주는 코드를 추가했습니다.
https://github.com/ACON3D/blender/blob/9925e22d17b72efbdf3ec25e5a59405db5dff86f/release/scripts/startup/abler/pref.py#L57-L60
[노션 카드 링크](https://www.notion.so/acon3d/ABLER-5deb660945e8448c91a141b44122ea4e)

단축키 키맵이 ABLER 인지 확인

---

release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/pref.py

노션 카드 : https://www.notion.so/acon3d/3D-f893a1ccecf4494cb0594a49d46c8107?p=9f4acf60a9154443943b4b8d1cc77604

adjust last operation 패널 숨기기

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py

space 단축키로 들어간 Anim Player 실행을 에이블러에서 제외하기로 논의했습니다.
기록을 위해 원래 코드는 주석으로 처리했습니다.
노션카드 : https://www.notion.so/acon3d/3D-7902f7a715a141b282c0b1537dd6c2b5?p=526657276c3f4e65bea97b7ca5ff16ed

Anim Player 단축키인 space 빼기

---

.gitignore
abler_dev_build.py
release/scripts/startup/abler/credential_modal.py
release/scripts/startup/bl_operators/wm.py

현재는 공지사항 중 가장 최신 공지 3개가 가장 위부터 나열되어있는 형태로 만들어져있습니다.
아래와 같은 형태입니다

공지사항 작업 진행중

---

launcher_abler/AblerLauncher.py
launcher_abler/mainwindow.py

- Downloading ABLER를 Downloading으로 변경
- Update ABLER Launcher을 Update Launcher로 변경
현재 가지고 있는 윈도우 머신이 없어서, 빌드를 못해보고 있습니다 ㅠㅠ (리모트 컴에서는 왠지 모르게 이미지가 깨짐) 
@Youdiie @seungha-kim 한번 빌드해서 테스트만 추후에 미팅하고나서 요청 드리겠습니다...!

AblerLauncher UI 깨지는 현상 변경

---

source/creator/CMakeLists.txt

윈도우에서 launcher-qt 를 빌드하는 내용이 있는데, 현재 make 시에 아래와 같은 에러가 나고 있어 관련 부분 주석 처리하였습니다.

Windows의 launcher-qt 내용 주석 처리

---

release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/import_external_files.py
release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/layers.py
release/scripts/startup/abler/lib/materials/materials_handler.py
release/scripts/startup/abler/lib/materials/materials_setup.py
release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/lib/render.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/shadow.py
release/scripts/startup/abler/object_control.py
release/scripts/startup/abler/operators.py
release/scripts/startup/abler/pref.py
release/scripts/startup/abler/render_control.py
release/scripts/startup/abler/scene_control.py

Camel Case 인 함수명들을 Snake Case 로 통일하여 코드의 전반적인 통일성을 향상시켰습니다.
(+ 함수명 중 Acon 이 들어간 경우에는 ACON 으로 변경하였습니다.)
(이전명 기준)
- lib/materials/materials_handler.py
```
toggleToonEdge
toggleEachEdge
toggleToonFace
toggelTexture 과 내부 변수
toggleShading 과 내부 변수
toggleEachShading
toggleEachShadow
changeToonDepth
setMaterialParametersByType
changeMatarialType
changeImageAdjustBrightness
changeImageAdjustContrast
changeImageAdjustColor
changeImageAdjustHue
changeImageAdjustSaturation
changeLineProps
changeToonShadingBrightness
```
- lib/materials/materials_setup.py
```
createOutlineNodeGroup
createToonFaceNodeGroup
createAconMatNodeGroups
removeAconMatNodeGroups
applyAconToonStyle
```
- lib/cameras.py
```
getCameraName
goToCustomCamera
makeSureCameraExists
turnOnCameraView
turnOffCameraView
switchToRendredView …
```

Camel Case => Snake Case 로 함수명 변경

---

release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/import_external_files.py
release/scripts/startup/abler/lib/login.py
release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/operators.py

- look at me
- use state on/off
- bloom on/off
- background images on/off
- file open
- import blend
- import fbx
- save
- save as
- logout
- file open fail
- import blend fail
- import fbx fail
- save fail
- save as fail
"최근 파일을 열기" 동작으로 파일을 열 때는 File Open, File Open Fail 이벤트가 발생하지 않습니다.

믹스패널 트레킹 작업 개선

---

release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/lib/login.py

is_first_open 의 함수 이름을 명확성을 위해  is_process_single 로 변경하고 docstring 을 추가하였습니다.

is_first_open 의 함수 이름 변경

---

release/scripts/startup/bl_operators/wm.py

Go to Guide > ABLER Guide 버튼명 수정요청 받아 업데이트 했습니다.
translation submodule 업데이트 하고 머지하겠습니다. 리뷰만 부탁드립니다.

튜토리얼 버튼명 수정

---

release/scripts/startup/abler/credential_modal.py

로그인 시에 사용되고 있던 트래킹 관련 Legacy 코드를 삭제하였습니다.

DELETE unnecessary condition in Logintask._task

---

release/scripts/startup/abler/camera_control.py

따로 설정값이 없는 상태에서 Large로 강제하게끔 코드 추가했습니다.

[0.2.4 QA] 배경이미지 팝업 창 이미지 크기 Large로 변경

---

release/scripts/startup/abler/camera_control.py

psd 이미지 로드 이슈로 목록에서 아예 제거했습니다.
노션 문서 : https://www.notion.so/acon3d/psd-load-24908606053a4d6495c2031a7e8f474a

[0.2.4 QA] psd 이미지 목록에서 제외

---

source/blender/editors/interface/interface_handlers.c

- show_password, remember_username, show_guide 액션도 undo 가 되지 않도록 Array 에 추가했습니다.
- strcmp 가 0 인지 체크하도록 수정했습니다.

Undo List 버그 수정

---

release/scripts/startup/abler/__init__.py

unregister()이 더이상 사용되지 않아서 __init__.py에 있는 unregister를 pass 처리했습니다.

__init__.py의 unregister() 함수를 pass로 처리함

---

pyproject.toml
release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/face_control.py
release/scripts/startup/abler/lib/import_file.py
release/scripts/startup/abler/pref.py

[노션 링크](https://www.notion.so/acon3d/black-7234051122a2455cb7096e0bfdcf15c9)
- IDE 내에서 black 자동 포매팅을 적용시켜놓았는데, 포매팅 되지 않은 파일들이 계속 git 에 트래킹됩니다.
- abler_default.py 파일도 black 의 범위에 추가될 수 있도록 pyproject.toml 을 수정했습니다.
- abler 및 launcher_abler 로 시작하는 파일/디렉토리에 black 적용
- black 포매팅이 되어있지 않았던 파일들을 포매팅하였습니다.

black 적용 안 된 파일 일괄 적용하기

---

release/scripts/startup/bl_ui/space_topbar.py

[링크](https://www.notion.so/acon3d/Language-Korean-Menu-fd9fab5dfb8b4cc99b2850bf8b7ec0f6)
- 파일 열기 번역 안되는 이슈
- Open... -> Open 네이밍 변경

파일 열기 네이밍 변경

---

release/scripts/startup/abler/lib/scenes.py

Reverts ACON3D/blender#137
다른 브랜치와 merge 과정에서 조건문을 같이 만족시켜줘야 해 일단 revert 돌리고 다시 PR 올리겠습니다!

Revert "씬 전환시 EDIT_MODE에서 런타임에러 발생하는 문제 "

---

release/scripts/startup/abler/pref.py

[에이블러 내 Infinity Zoom 기능 활성하기](https://www.notion.so/acon3d/Infinity-Zoom-d46633bb014f49b9a3401a5fdecc1f24)
- 스케치업과 같이 큰 공간의 모델을 기반으로 작업할 때는 내부의 navigating 이 필요함
- 에이블러도 스케치업과 유사한 환경을 제공하기 위해 다음과 같은 사항이 필요함
- **`Orbit & Plan > Auto > Depth`** : **`Default : Checked`**
- **`Zoom > Zoom Method`** : **`Default : Dolly`**
요청 사항의 옵션들은 모두 `Menu` > `Edit` > `Preference` > `Navigation` 하위에 있음
- `Orbit & Pan` > `Auto` > `Depth` 의 기본값 **True**
- 아래의 사항을 적용하면됨.
```python
def init_setting(dummy):
prefs = bpy.context.preferences
prefs_input = prefs.inputs
...
bpy.context.preferences.inputs.use_mouse_depth_navigate = True
```
- `Zoom` > `Zooom Method` 의 기본값 **Dolly**
- 이미 `Dolly` 로 설정되어 있어서 별다른 처리할 필요 없음.

Infinity Zoom 모드 활성

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/lib/tracker/_tracker.py

[태스크 카드](https://www.notion.so/acon3d/d06dd10b1188489185eee057fa844cbe)
텍스처 렌더 기능을 구현했습니다.
다국어 처리는 따로 하지 않았는데, 렌더링 쪽 새로운 UI 구현되면서 다같이 들어갈 예정일까요?

Render texture 추가

---

release/scripts/modules/bl_i18n_utils/settings.py
release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/camera_tab/camera_control.py
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/scene_tab/layer_control.py
release/scripts/startup/abler/scene_tab/object_control.py
release/scripts/startup/abler/scene_tab/scene_control.py
release/scripts/startup/abler/style_tab/styles_control.py
source/blender/editors/interface/interface_eyedropper_datablock.c
source/blender/editors/interface/interface_template_list.cc
source/blender/editors/interface/interface_templates.c
source/blender/editors/space_view3d/view3d_edit.c
source/blender/makesrna/intern/rna_camera.c
source/blender/makesrna/intern/rna_material.c
source/blender/makesrna/intern/rna_nodetree.c
source/blender/makesrna/intern/rna_object.c
source/blender/makesrna/intern/rna_scene.c
source/blender/makesrna/intern/rna_userdef.c

[사양서 링크](https://drive.google.com/drive/u/0/folders/19EY5BXxyf-ikJO1afEwUqWr6vi8A3kDQ)
[다국어 문서 링크](https://docs.google.com/spreadsheets/d/156yvAxJgrG-RG2eJYJkMC0GtTBsxlQMPbjtVX1OzO-E/edit#gid=853560161)
[blender-translation 관련 PR](https://github.com/ACON3D/blender-translations/pull/32)
- 다국어 자동화 이전에 현재 사양서에 있는 내용과 싱크를 맞추자
-

UI 이름 사양서과 싱크 맞추기

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py
release/scripts/startup/abler/lib/tracker/_tracker.py

[노션 태스크 카드](https://www.notion.so/acon3d/skp-import-d679321a1c8d4f829e842e277cbfdd46)
- 믹스패널에 import_skp가 없음
- 믹스패널에 import_skp를 추가함
- 갖가지 에러 관리를 위해서 import_skp 감싸는 오퍼레이터를 분리함
- 사소한 그 전에 들어간 잔실수들을 수정함.

skp import를 믹스패널에 추가하고, 몇가지 TODO도 추가함.

---

release/scripts/startup/abler/general_tab/general.py

[링크](https://acontainer.slack.com/archives/C02K1NPTV42/p1668048904420269)
- general에서 importFBX가 남아있어서 지워주었습니다.
- UI에서 지우기

importFBX UI에서 지우기

---

release/scripts/startup/abler/export_tab/render_control.py

[링크](https://www.notion.so/acon3d/opaque-85f8d30e7e534f3ba42648a9aec53189)
- 풀렌더에서 투명 재질이 반영이 안됨

풀렌더에서 재질이 opaque로 들어가는 에러

---

release/scripts/startup/abler/general_tab/general.py

[논의 링크](https://acontainer.slack.com/archives/C01K142MCNS/p1667969531139289?thread_ts=1667956338.378559&cid=C01K142MCNS)
- 있던 look at me를 느리다는 이유로 빼기에는 유저 경험이 해쳐질 수 있으니, 선택할 수 있는 선택지를 주자
- import 오퍼레이터에 해당 파라미터를 제공하고, 최하단까지 전달되도록 미리 만들어두었습니다.

import skp에서 import_lookatme 옵션을 제공할 경우에 대한 UI 및 Operator까지의 연결부분 작업

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/file_view.py
source/blender/makesrna/intern/rna_wm_api.c
source/blender/windowmanager/WM_types.h
source/blender/windowmanager/intern/wm_event_system.c

[태스크 카드 링크](https://www.notion.so/acon3d/44adc8df476944d3bee6fb2a3431de85)
- 파일 뷰 (파일 선택기) 의 제목을 상황마다 다르게 넣을 수 있도록 수정했습니다.

파일 뷰의 타이틀을 상황에 맞게 변경

---

release/scripts/startup/abler/lib/file_view.py

- title_enum 이 keyword parameter 여야 함

파일 다이얼로그가 제대로 동작하지 않는 문제

---

release/scripts/startup/abler/scene_tab/scene_control.py

[링크](https://www.notion.so/acon3d/820d390da40147b3a61939170000eb66)
- 같은 이름의 씬 생성 후 삭제 시 에러 발생
- 씬 생성 시 같은 이름 있을 때 postfix 추가

씬 추가 생성 후 삭제 시 에러

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/file_view.py
release/scripts/startup/abler/lib/read_cookies.py
release/scripts/startup/abler/scene_tab/object_control.py
release/scripts/startup/abler/startup_flow.py

[슬랙 쓰레드](https://acontainer.slack.com/archives/C02K1NPTV42/p1668578707648689)
- black 이 적용되지 않았던 코드들이 있음
- 위 코드들에 black 을 적용함

black 이 적용되지 않았던 코드 일괄 적용

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/camera_tab/camera_control.py
release/scripts/startup/abler/style_tab/styles_control.py

[링크](https://www.notion.so/acon3d/UI-4cb8bbf00d8f4693afb72f90e8e0d193)
- 제목 열에 텍스트가 아니라 토글로 되어 있는 문제(Styles, Camera Control, Background)
- Style 탭> Styles 명칭 변경

기획서랑 UI 차이나는 문제

---

release/scripts/startup/abler/general_tab/general.py

[태스크 링크](https://www.notion.so/acon3d/Menu-Import-SKP-look-at-me-3a0d57eb086649229ec7c784414ca70d)
- 메뉴를 통해 Import SKP 에 접근한 경우 look at me 를 선택할 수 없음
- draw 함수를 추가하였습니다.

Menu - Import - SKP 에서 look at me 를 선택할 수 없는 문제

---

release/scripts/startup/abler/lib/tracker/_tracker.py

[노션 논의 링크](https://www.notion.so/acon3d/221122-R-D-a508bc2d8e2a49edacde86dac3a74328#17d8e941d2b940cd9452077c1c838d4b)
- 믹스패널 테스트용 로그 파일을 만들 수 있어야 함.
- --log를 붙여서 에이블러를 실행하면 믹스패널 로그파일을 바탕화면에 출력하도록 기능 추가

믹스패널 테스트용 아규먼트 추가

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/startup_flow.py

[링크](https://docs.google.com/spreadsheets/d/156yvAxJgrG-RG2eJYJkMC0GtTBsxlQMPbjtVX1OzO-E/edit#gid=1769912811)
- 다국어 검수 브랜치 통합을 위한 PR입니다. 팝업 메세지 파트 작업한 내용입니다.
-

팝업 메세지 다국어 검수

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py

[링크](https://docs.google.com/spreadsheets/d/156yvAxJgrG-RG2eJYJkMC0GtTBsxlQMPbjtVX1OzO-E/edit#gid=2140991995)
- 다국어 검수 브랜치 통합을 위한 PR입니다. 파일 뷰어 파트 작업한 내용입니다.
-

파일 뷰어 다국어 검수

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/startup_flow.py
release/scripts/startup/bl_operators/wm.py
release/scripts/startup/bl_ui/space_filebrowser.py
source/blender/editors/interface/interface_template_list.cc
source/blender/editors/space_file/file_ops.c

[다국어 검수](https://www.notion.so/acon3d/7b211dbaecaa4bdb9fb224e0f96e4b9c)
- 다국어 검수 1차
- 상단 메뉴 및 파일 브라우저 번역 작업

상단 메뉴 및 파일 브라우저 번역 작업

---

intern/cycles/blender/addon/ui.py
release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/startup_flow.py
release/scripts/startup/bl_ui/space_filebrowser.py
source/blender/editors/interface/interface_region_tooltip.c
source/blender/makesrna/intern/rna_camera.c
source/blender/makesrna/intern/rna_scene.c

#270 
#272 
- 다국어 전체 시트 2차 확인
- 추가 수정 및 누락 반영

다국어 2차 확인 & 추가 수정

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py

- Open Acon3d와 Search on Acon3d 기능을 track 해야 됨
-  Open Acon3d와 Search on Acon3d 기능의 tracker 추가함

에이블러에서 에이콘으로 연결되는 두가지 기능 추가에 대한 믹스패널 트래커 추가

---

release/scripts/startup/abler/scene_tab/object_control.py

[Active object가 없는데 type에 접근하는 문제 - 노션 카드](https://www.notion.so/acon3d/Active-object-type-34991dc0f3244f7e883e066924bf0048?pvs=4)
- `add_group_list_from_collection()`함수에서 active object가 없는데 type값에 접근하려다 에러가 발생함.
- obj의 존재여부를 확인하는 `If문` 추가

Active Object가 없는데 오브젝트의 type속성에 접근하려는 문제

---

.gitmodules

GitHub organization 이름을 변경하면서 submodule 링크를 알맞게 걸어주기
- GitHub username을 변경하면서 submodule URL 변경
- 최신 submodule commit 반영

[SWTASK-78] Update submodule URL & commit

---

release/scripts/startup/abler/pref.py

[일정 범위 이상 줌아웃시 개체가 안보이는 에러-테스크 카드](https://www.notion.so/acon3d/3d433a89042a4fd4a6a9a38b282c09f3)
- 트위터 CS: 시야 확보 문제
- 카메라 렌즈 값의 범위 조정
- `camera.clip_end`범위를 조정하여 초기 카메라 clip_end를 100000m로 적용

SWTASK-34 줌아웃을 해도 오브젝트가 보일 수 있도록 카메라 렌즈 값 조정

---

release/scripts/startup/abler/lib/tracker/_get_ip.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-84)
- 믹스패널 국가 트래킹이 되지 않고 있음
- [ipify - A Simple Public IP Address API](https://www.ipify.org/) 의 univeral 코드를 사용

ip를 받는 url 주소를 변경

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py

Reverts carpenstreet/blender#289

Revert "SWTASK-36 SWTASK-37 파일명 뒤에 공백이 들어가는 발생하는 문제"

---

release/scripts/startup/abler/lib/materials/materials_handler.py

[nodeTree 리팩토링 - 관련 jira 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-206)
- 에러와 관련된 코드를 보시던 중 제가 작업한 코드에서 리팩토링이 필요한 부분을 발견하셔서 알려주심
- 재사용할 수 있는 variable 이름으로 수정함

SWTASK-206 materials_handler.py 코드 리팩토링

---

release/scripts/startup/abler/startup_flow.py
source/blender/makesrna/intern/rna_wm_api.c

[이슈](https://carpenstreet.atlassian.net/browse/SWTASK-316?atlOrigin=eyJpIjoiYTRjMDNiMjE0NzI2NDk4MWI3OGEzYjhhZTVjNmVlYTMiLCJwIjoiaiJ90)
[다국어 관리 문서](https://docs.google.com/spreadsheets/d/156yvAxJgrG-RG2eJYJkMC0GtTBsxlQMPbjtVX1OzO-E/edit#gid=1769912811)
[Translation PR](https://github.com/carpenstreet/blender-translations/pull/54)
- 업데이트 관련 함수 문구 수정
- Sparkle Updater 를 사용하는 함수의 description 을 Check for Updates 로 변경
- Update ABLER with ABLER Launcher => Update ABLER 로 변경

SWTASK-316 에이블러 업데이트 함수 description 수정

---

launcher_abler/AblerLauncher.py
launcher_abler/AblerLauncherUtils.py
launcher_abler/UpdateAbler.py
launcher_abler/UpdateLauncher.py
launcher_abler/requirements.txt

[지라 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-266?atlOrigin=eyJpIjoiOTRmOTU2MWNmMjVjNDQ4NDhlZWNkODMxZDYyY2RjODUiLCJwIjoiaiJ9)
- 다운로드 인프라가 바뀌게 됨
- XML 파일을 올려서 인프라를 사용하게 됨
- URL이 바뀜
- macOS / Linux 등에 대한 코드를 전부 삭제함 (이제 에이블러 런쳐는 Windows 전용임)
- 각종 비합리적인 코드를 수정함
- XML을 파싱하여 현재 최신 버전을 받아올 수 있도록 로직을 수정함.

SWTASK-266 윈도우 런쳐 파싱 및 링크 수정

---

release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/style_tab/styles_control.py

조명기능 아이템 이름변경 추가
조명기능 팝업 documentation 추가

[SWTASK-399] 조명기능 이름변경 및 팝업설명 추가

---

release/scripts/startup/abler/pref.py

바닐라 블렌더 로드시 경고창 출력
에이블러에서 블렌더 파일 로드시, 툰쉐이딩 과정중 ACON material이 추가되면서 노드 정보가 바뀜
이를 위해 유저에게 경고 다이얼로그 출력

SWTASK-360 바닐라 블렌더 파일 로드시 경고창 출력

---

release/darwin/ABLER.app/Contents/Info.plist
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/pref.py
release/scripts/startup/abler/style_tab/styles_control.py
source/blender/blenkernel/BKE_undo_system.h
source/blender/blenkernel/intern/undo_system.c
source/blender/editors/interface/interface.c
source/blender/makesrna/intern/rna_wm_api.c
source/blender/windowmanager/intern/wm_files.c

0.3.5 QA 작업분 main에 반영

---

release/scripts/startup/bl_operators/wm.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-523)
- 공지사항 갯수가 늘어나 정리 필요
- [블렌더 릴리즈 노트] 항목 제거

SWTASK-523 블렌더 릴리즈 노트 항목 제거

---

release/scripts/startup/bl_operators/wm.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-656)
[번역 PR](https://github.com/carpenstreet/blender-translations/pull/64)
- 
- 스플래시 항목 수정
- 가이드 링크 수정
- 튜토리얼 팝업 링크랑 통합

[SWTASK-656] 스플래시 수정

---

release/scripts/startup/abler/export_tab/render_control.py

0.3.7 릴리즈 버그 수정
https://acontainer.slack.com/archives/C04L2A538G0/p1695640119763979

렌더시 비정상종료되는 버그 수정

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/lib/layers.py
release/scripts/startup/abler/lib/render.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/pref.py
release/scripts/startup/abler/scene_tab/object_control.py
release/scripts/startup/abler/style_tab/styles_control.py
release/scripts/startup/bl_operators/wm.py
release/scripts/startup/bl_ui/space_toolsystem_toolbar.py

Revert 385 abler/develop

---

release/scripts/startup/abler/export_tab/render_control.py

[링크](URL)
- show_guideline에서 발생하는 에러 해결
-

show guideline 에러 해결

---

release/scripts/startup/abler/export_tab/render_control.py

0.3.8 가즈아2

---

release/scripts/startup/abler/export_tab/render_control.py

[Jira 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-743)
- 퀵 렌더의 폴더 저장 방식이 불편하다는 CS가 다수 인입
- 예전 [PR](https://github.com/carpenstreet/blender/pull/365)을 참고해서 이전 저장 방식으로 돌림
- 조명 추가 관련 show_guideline 함수를 제 때에 꺼주는 로직 추가
1. 퀵렌더 확인
- 에이블러를 켠다
- 씬에 조명을 추가한다
- 퀵 렌더를 하고, 파일명을 입력해서 저장하는 방식인지 확인한다
- 렌더 결과물에 조명 기즈모가 없는지 확인한다.
2. 풀렌더 확인
- 1이 끝난 상태에서 풀렌더를 돌린다.
- 폴더 입력 방식이 그대로인지 확인한다.
- 렌더 결과물에 이상이 없는지 확인한다.

SWTASK-743 퀵 렌더의 저장 방식을 파일 명 입력 방식으로 바꿈
