carpenstreet/blender

build_files/windows/check_libraries.cmd

윈도랑 맥이랑 make update 작동방식이 조금 다른데, 제가 이전에 lib 받아오는 부분 수정할 때 맥에서 작업해서 미처 이 부분을 발견하지 못했습니다.
이 변경사항이 있기 전에는 윈도에서 아래와 같이 동작했습니다.
- 윈도에서 `make.bat update` 를 실행하면
1. `check_libraries.cmd` 에서 `trunk` 기준으로 `svn checkout` 을 실행
2. `make_update.py` 에서 `tags/blender-3.0-release` 기준으로 `svn checkout` 을 한 번 더 실행
(참고로, 맥에서는 2만 실행됩니다)
이 때문에, 필요없는 최신 lib 파일들을 한 번 받은 다음 예전 버전인 3.0 기준의 lib 파일들을 한 번 더 받게 되는 불필요한 과정이 실행됩니다. 그 과정에서 @habijung  이 겪으신 것처럼 svn 상태가 꼬이는 문제가 생겼던 것으로 보입니다.
애초에 윈도에서도 1번 과정이 없으면 베스트겠지만, 1번과 2번 사이에 동작하는 스크립트들 중에 lib 폴더가 있어야만 동작하는 부분들이 있어서, 1번 과정에서도 (이번에 새로 추가한) `.lib-version` 파일을 기준으로 svn 브랜치를 선택하도록 수정했습니다.
같은 픽스를 2.93 에이블러에도 바로 넣겠습니다~~

윈도에서 make update 할 때 trunk 에서 lib 가져오는 문제 수정

---

release/scripts/startup/abler/render_control.py

`General > Render` 기능 사용 시 파일명이 아닌 폴더 명으로 저장되는 문제 해결
- 파일 / 폴더 저장 구분을 위해서 `Acon3dRenderOperator` 의 하위 클래스로 `Acon3dRenderFileOperator` 와 `Acon3dRenderDirOperator` 로 구분
- `Acon3dRenderFileOperator` 는 문자열에 확장자 추가를 위해 `ExportHelper` 사용
- 마찬가지로 `Acon3dRenderTempSceneFileOperator` 클래스 추가하고, `Acon3dRenderTempSceneOperator` → `Acon3dRenderTempDirOperator` 로 변경한 이유는 상속받는 클래스 `ImportHelper` 와 `ExportHelper` 가 다르기 때문
- Panel 에 명시된 순서로 클래스 위치 조정
- Quick, Full, Line, Shadow → 파일로 저장
- All Scene, Snip → 폴더로 저장
- 파일 저장 시 현재 Scnen 이름 가져오기 (확장자 `.png` 포함)
- 폴더 저장 시 현재 Blender 파일 이름 가져오기 (확장자 제외)
- 저장할 때 파일 및 폴더 이름 변경 가능
- 임시 파일 `untitled` 에 대해서도 문제 해결

렌더별 파일 및 폴더 구분 저장

---

release/scripts/startup/abler/credential_modal.py

- https://github.com/ACON3D/ABLER/pull/127
- 에이블러를 로그인 없이 사용 가능한 문제가 있었습니다.
- 오류 : `ord() expected a character, but string of length 0 found`
- char2key(c) 에서 키보드 값이 없을 때 splash 창 띄워주기
- 마우스 왼쪽, 중간, 오른쪽 모든 클릭에 대해서 splash 창 띄워주기
- splash 창이 없을 때 키보드를 연타해도 splash 창 생성

로그인 없이 사용하는 문제 해결 (Blender-3.0)

---

release/scripts/startup/bl_operators/wm.py
source/blender/windowmanager/intern/wm_splash_screen.c

에이블러 버전 표시 및 블렌더 버전 삭제했습니다.
`abler_version` 함수에서 이전에 쓰이던 get_version을 쓰되 None일 경우 `Production version`을 반환하도록 했습니다.
노션 카드 : https://www.notion.so/acon3d/e77b7857a9634fd5b88d653bdf560538

스플래시 화면에 에이블러 버전 표시

---

release/scripts/startup/abler/lib/render.py

- 배경이미지를 추가하고 `Unpack Item` 기능 **(1회성)** 을 사용하여 배경이미지를 추출한 뒤, 파일의 이동/삭제 등으로 이미지 파일 로딩이 불가능 하면 발생
- 오류 내용 : `ZeroDivisionError: division by zero`
- 배경이미지 로딩이 불가능하면 파일 정보가 없기 때문에 `image.size` 값이 없습니다. 해당 문제가 발생할 경우 다음 이미지 로딩으로 건너뜁니다.

배경 이미지가 없을 경우 해당 이미지 로딩 건너뛰기

---

launcher_abler/AblerLauncher.py

런쳐에서 run abler시에 두 세션이 열리는 현상을 방지했습니다
subprocess가 두번 등록되어서 두 개의 세션이 열리는 현상이었습니다.

두 세션 열리는 현상 해결

---

release/scripts/startup/abler/lib/materials/materials_setup.py

블렌더 3.0으로 이관하면서 쉐이더 노드의 이미지가 자동으로 MixFactor1에 연결되어 재질의 Reflection이 잘 반영되지 않았습니다.
요 연결부를 처음 시작할때 끊어주었습니다.
노션 카드 : https://www.notion.so/acon3d/reflection-198f5300512248b39e9d6149090b1048

reflection 적용 오류 개선

---

release/scripts/startup/abler/custom_properties.py

https://acontainer.slack.com/archives/C02K1NPTV42/p1649831589660969
슬랙에서 나온 얘기 반영해서 toon-shading-depth `default="3"`로 추가해주었습니다.
혹시나해서 startup.blend에서도 3 depth로 저장하고 변경했습니다.

toon-shading-depth default 추가 

---

launcher_abler/AblerLauncher.py

런쳐에서 릴리즈가 없을 때의 request의 response에 "message" 라는 항목이 없어서 update launcher 버튼만 떠있고 아무것도 진행이 안되는 문제를 해결했습니다.
빠르게 리뷰 부탁드릴게요!! 이거 기반으로 다시 릴리즈 파일 만들어서 올려야 할 것 같아요

updated request not found exception

---

pyproject.toml

`launcher_abler` 폴더에서도 `black`이 사용 가능하도록 업데이트 했습니다.

launcher_abler 폴더에서 black 사용

---

launcher_abler/AblerLauncher.py

- 에이블러 런처로 실행시에 업데이트 도중 Quit 혹은 프로그램을 종료하게 되면 업데이트가 취소되고 원래 버전 정보가 있어야함
- 그런데, 업데이트 버튼을 누르면 곧바로 `config.ini`가 새 버전으로 업데이트 되어 런처를 재실행하면 업데이트를 정상적으로 할 수 없는 문제가 있음
- 관련 문서 : [노션](https://www.notion.so/acon3d/a6447b8789de488aadeee1177cffc4ac)
- `config.set` 코드를 `Tread`가 끝나는 시점에 실행해야함
- `done_abler`, `done_launcher` 함수 내로 옮기면 해결
- `configparser.ConfigParser()` 가 런처와 에이블러에서 중복 정의되기 때문에 하나의 함수 `def update_config`로 간소화
- `AblerLauncher.py` 내부에서 `finallist[0]` 만 `entry`로 사용되기 때문에 `self.entry`로 정의하고 변수 대체

업데이트 완료 후 config.ini 버전 정보 업데이트

---

launcher_abler/ConfigSelector.py

- Notion : [명령어로 런처 버전 업데이트](https://www.notion.so/acon3d/cda3e9c96072483594d314e25b386df9)
```bash
$ cd ~/blender/launcher_abler
$ python ConfigSelector.py --copy
$ python ConfigSelector.py --run --update launcher abler
```
```bash
$ python ConfigSelector.py --help
usage: Parser [options]
ABLER launcher update test.
optional arguments:
-h, --help            show this help message and exit
--print, -p
--copy, -c
--reset, -r
--remove
--update [UPDATE ...], -u [UPDATE ...]
--run
```
- `--print` : 자세한 사항 표시
- `--copy` : 현재 `config.ini` 를 백업. 백업 파일이 없으면 실행 필요
- `--reset` : 백업 파일로 `config.ini` 리셋 및 백업 파일 삭제
- `--remove` : 백업 파일 삭제
- `--update` : 업데이트할 조건 추가 (`abler` or `launcher`)
- `--run` : `AblerLauncher.exe` 실행

명령어로 런처 버전 업데이트

---

launcher_abler/AblerLauncher.py
launcher_abler/AblerLauncherUtils.py
launcher_abler/UpdateAbler.py
launcher_abler/UpdateLauncher.py

- Pre-Release를 생성하거나 새 저장소로 옮길 때 런처를 통한 업데이트가 잘 되는지 테스트하는 과정이 필요
- URL 세팅으로 에이블러 저장소 (blender) 혹은 테스트 저장소 (launcherTestRepo) 의 릴리즈 정보를 받아올 수 있음
- 관련 Notion 문서: [새 repo로 런처, 에이블러 업데이트](https://www.notion.so/acon3d/repo-8f7449ca793d4e55b96bb0ebb03e0904)
```bash
$ cd C:/Users/{username}/AppData/Roaming/Blender Foundation/Blender/2.96/updater
$ ./AblerLauncher.exe --new-repo-release
$ ./AblerLauncher.exe --new-repo-pre-release
$ cd ~/blender/launcher_abler
$ pyinstaller --icon=icon.ico --onefile --uac-admin AblerLauncher.py
$ ./dist/AblerLauncher.exe --new-repo-release
$ ./dist/AblerLauncher.exe --new-repo-pre-release
```
```bash
$ ./AblerLauncher.exe --pre-release
```

런처에 릴리즈 관련 argument 추가

---

launcher_abler/AblerLauncher.py
launcher_abler/AblerLauncherUtils.py
launcher_abler/UpdateAbler.py
launcher_abler/UpdateLauncher.py

@sdkfile 과 페어 코딩 및 확안으로 브랜치 이름 변경 없이 PR 올립니다.
[#48 런처에 릴리즈 관련 argument 추가](https://github.com/ACON3D/blender/pull/48)에 rebase된 브랜치이기 때문에 해당 PR이 머지되고 확인하시면 될 것 같습니다.
- `StateUI.no_release` 의미가 직관적이지 않아서 `StateUI.empty_repo`로 수정
- 빈 저장소 테스트 argument 이름 변경
- 빈 저장소 pre-release 테스트에서 request의 에러 처리

빈 저장소의 프리 릴리즈 request 에러 처리

---

launcher_abler/AblerLauncherUtils.py

- 런처 레포 테스트에 사용되는 변수가 `len(argv) > 1`일 때만 생성되어서 다른 곳에서 변수를 찾을 수 없는 문제가 있었습니다.
- 관련 인자들을 `None`으로 초기화 시켜주었습니다.

런처 레포 테스트에 사용되는 변수 초기화

---

launcher_abler/AblerLauncher.py

- 런처 업데이트 UI가 표시되지 않는 문제 수정
- `state_ui`가 `StateUI.empty_repo`와 비교가 되어야 하는데 해당 부분이 빠져있었음

(release/v0.2.2) 런처 업데이트 UI가 표시되지 않는 문제 수정

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/general.py
release/scripts/startup/bl_ui/space_topbar.py

- 파일 저장 시, 파일 브라우저에서 파일명이 중복이어도 경고 표시만 있고 안내 없이 덮어쓰기로 저장됨
**예시) `a.blend`**
- 최초 저장 ▶ `a.blend`
- `a.blend`가 존재하고 `a.blend` 로 저장 ▶ `a (2).blend`
- `a (2).blend`가 존재하고 `a (2).blend` 로 저장 ▶ `a (2) (2).blend`
- `a.blend`, `a (2).blend`가 존재하고 `a.blend` 로 저장 ▶ `a (3).blend`
- `ExportHelper` 추가
- `New` 파일이면 파일 경로가 없기 때문에 `untitled.blend` 추가를 위한 `invoke()` 구분
- 한번 저장된 이력이 있으면 파일 경로 그대로 받아서 `Save`
- 한번도 저장된 이력이 없으면 파일 브라우저 실행 후 파일명 처리 실행 및 `Save`
- `ExportHelper` 추가
- `New` 파일과 구분할 필요가 없기 때문에 바로 파일 브라우저 실행 후 파일명 처리 및 `Save As` 실행

파일 중복 저장 시 숫자 추가

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py

기존의 unselect인 Alt+A에서 ESC로 단축키 변경했습니다.
ESC가 다른 동작과 안겹치는 것도 확인됐습니다.
노션 카드: https://www.notion.so/acon3d/ESC-c8cf0594ea084f68a5c37f9818c4ac9b

unselect ESC로 변경

---

release/scripts/startup/abler/general.py
release/scripts/startup/bl_ui/space_topbar.py

https://github.com/ACON3D/blender/blob/4dadd22a2ef9c68476dc0749b3279697ceece1ac/release/scripts/startup/abler/general.py#L139-L153
[링크](https://www.notion.so/acon3d/01932ec7155441e798cd4f1b072b40d2)

파일 열기 시 빈 곳을 더블 클릭하면 파일이 없는 문제

---

release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/operators.py
release/scripts/startup/bl_ui/space_topbar.py

- 로그인은 있지만 로그아웃이 없어 로그아웃 기능 구현
- 로그아웃 기능 UI 위치 논의 완료
- 자세한 내용은 Notion 문서: [로그아웃 기능 구현](https://www.notion.so/acon3d/e04062c4d446419cbd8768447da7f076)
- 로그아웃 Operator
https://github.com/ACON3D/blender/blob/62c8b090ca3bf7acb65d1e44bc119fbf6fab87b5/release/scripts/startup/abler/operators.py#L19-L51
> 아래의 문제들은 추후 필요 시에 다룰 예정
1. 파일 브라우저와 스플래쉬 창이 겹침
2. 스플래쉬 창이 뜬 상태에서 프로그램 종료창 발생

로그아웃 기능 구현

---

release/scripts/startup/abler/render_control.py

이전에 self.initial_scene.name으로 업데이트 해주는 코드는 Acon3dRenderOperator에서 상속받은 Acon3dRenderTempSceneFileOperator/Acon3dRenderTempSceneDirOperator 클래스(쉐도우, 라인, 스닙렌더 구현을 위한 클래스)에서 구현을 해 Acon3dRenderOperator에서 바로 동작하는 render all scenes에선 업데이트가 안되는 문제였습니다.
Acon3dRenderOperator에서 렌더가 끝난 시점인 on_render_finish 함수에 self.initial_scene.name로 업데이트 하는 코드 추가해주었습니다.
노션 카드 : https://www.notion.so/acon3d/Render-All-Scene-4274bbfb8c514a29bbd5a4d06f94ec20

render all scenes 이후 초기 씬으로 업데이트

---

release/scripts/startup/abler/object_control.py

@classmethod는 아예 오퍼레이터를 지워버리므로 draw 내부에서 Active Object가 없을 때에 대한 처리를 해주는 것으로 변경.
look at me에서 context.object로 조건문을 두면 선택된 개체가 없어도 버튼을 누를 수 있기 때문에 prop에선 선택된 개체가 없을 때 바로 안 보여야 유저가 헷갈리지 않아 조건문에서 context.selected_objects로 설정(해당 내용 코드 주석으로도 넣었습니다)
기능적으로 이상 없으면 번역 PR 추후에 올리겠습니다.
노션카드 : https://www.notion.so/acon3d/UI-f8ce6048da1e4636a11e1ca6d66b4aa0

Active Object가 없을 때 오브젝트 설정 UI 변경

---

release/scripts/startup/abler/lib/render.py
release/scripts/startup/abler/render_control.py

노션에 해당 발생 오류 및 개선 방법 정리했습니다.
https://www.notion.so/acon3d/3D-f893a1ccecf4494cb0594a49d46c8107?p=f9b9799dc6c54732b94d488febc2e203
밝기가 차이나는 현상은 Compositor-MIX nodes에서 bloom의 밝기가 mix되기 때문이었고, Compositor-MIX nodes 없이 바로 렌더해도 view_layer에서 영역만큼 잘라내기 때문에 이상 없습니다!

snip 렌더 밝기 오류

---

release/scripts/startup/abler/layer_control.py
release/scripts/startup/abler/lib/post_open.py

에이블러 전용 파일이 아닌 블렌더 파일엔 "Layers" 콜렉션이 없어서 에러가 발생했습니다.
아래처럼 "Layers" 콜렉션이 있는지 확인 후 없으면 l_exclude를 모두 지워버려 레이어 패널을 비활성화하도록 suppress 처리해주었습니다.
노션문서 : https://www.notion.so/acon3d/blend-Layers-1844e2b19ed24098b6dd67bd40626119

"Layers" 이름의 콜렉션 확인으로 에이블러 파일인지 확인

---

release/scripts/startup/abler/lib/shadow.py
release/scripts/startup/abler/pref.py

뷰포트 그림자에 알 수 없는 그림자 노이즈가 같이 생기고 있었습니다.
- 해당 Notion 문서: [불량 그림자 문제 조사 및 해결](https://www.notion.so/acon3d/58acc16606864bc8a14ec48615f2e6ad)
ACON_sun의 Shadow -> `Contact Shadows` 옵션이 On 되어 있었고, 이 옵션이 생성하는 그림자가 **불량 그림자** 라고 정의되던 그림자였습니다.
그래서 해당 옵션을 끄고, Shadow -> `Bias` 옵션을 **1.0 -> 0.1**로 주었습니다.
- startup.blend에서 Shadow → Bias = 0.001, Contact Shadows Off
- lib/shadows.py에서
```python
def setupSharpShadow():
acon_sun.data.use_contact_shadow = False
acon_sun.data.shadow_buffer_bias = 0.1
def createAconSun() -> Object:
acon_sun.data.use_contact_shadow = False
acon_sun.data.shadow_buffer_bias = 0.1
```
- Black 적용

불량 그림자 문제 조사 및 해결

---

release/scripts/startup/abler/lib/cameras.py

관련 Notion 문서: [View Camera 활성화를 SKP 컨버터에서 에이블러로 이동](https://www.notion.so/acon3d/View-Camera-SKP-008a9a9237df4d70a0c1221f5576fc9f)
SKP 컨버터를 백그라운드로 실행할 때, View Camera 활성 관련 오퍼레이터 에러가 발생
`bpy.ops.view3d.view_camera.poll()`
`bpy.ops.view3d.view_center_camera.poll()`
이렇게 두 곳에서 `context is incorrect` 관련 문제가 있음
컨버터는 백그라운드에서 실행되고, 파일을 여는 곳은 에이블러이기 때문에 카메라 활성을 컨버터에서 에이블러로 옮기기
그럼 에이블러 실행 시 View_Camera 활성하면 다른 카메라 오브젝트들이 나타나지 않을 것임
`bpy.context.view_layer.objects.active` 를 View_Camera 로 업데이트
백그라운드에서 문제 없이 컨버팅 되고, View_Camera가 정상적으로 활성화됨
```bash
$ run --background --python background_import_skp.py -- ~/test.skp
Blender 2.96.1 (hash 49bbf7185704 built 2022-06-27 00:23:40)
Read prefs: C:\Users\habi\AppData\Roaming\Blender Foundation\Blender\2.96\config\userpref.blend
SU | Importing: …
```

View_Camera 오브젝트 활성화

---

release/scripts/startup/abler/render_control.py

센트리에서 발견된 오류 핸들링입니다.
모종의 이유(유저가 에이블러 외 기능을 누른것으로 추정)로 render_queue가 빈 리스트에서 렌더가 동작해 오류가 발생해 render_queue가 빈 리스트인지 확인하는 코드 추가했습니다.
노션 문서 : https://www.notion.so/acon3d/post_render-render_queue-25a2c82563034d59881a1a35ec0c3b3b

post_render 시 render_queue 빈 리스트인지 확인

---

source/blender/editors/interface/interface.c

[노션 카드](https://www.notion.so/acon3d/Sentry-0-2281601ae6764f6ab7123458eb2d4cae)
[센트리 오류](https://sentry.io/organizations/carpenstreet/issues/2789541463/?project=6046815)
해당 오류는 아래와 같이 파이썬에서 기본으로 발생하는 오류였음
- 파이썬으로 블렌더가 넘기기 전에 앞에 있는 0들을 모두 strip 해버리는 기작을 추가하면 될 것이라고 생각함.
- UI에서 python으로 숫자를 넘기기 직전의 상태의 함수에서 변경사항과 같은 기작을 추가해서 leading zero를 참조하지 않도록 pointer를 옮김

숫자 앞에 0 표기 오류

---

launcher_abler/ConfigUpdater.py

런처에서 `ConfigUpdater.py` 로 업데이트를 할 때, Pre-release를 받아오지 못하고 있어 해당 내용 추가하기
Notion: [런처로 업데이트 할 때 Pre-release 정보 받아오기](https://www.notion.so/acon3d/Pre-release-0b76a4b1240a4f94bb79c07f0bc2856b)
- `config.ini` 수정 시, 다운그레이드 버전 0.0.1 → 0.0.0 으로 수정.
- AblerLauncher.exe 실행할 때, `--pre-release` 옵션을 추가해서 프리릴리즈의 설치 정보를 받아올 수 있게함

config 파일 업데이트 시, pre-release 받아오기

---

release/scripts/startup/abler/lib/tracker/_tracker.py

Use State 토글 시 선택된 object 마다 트래킹을 모두 보내서,
해당 부분에 accumulate decorator 를 넣어서 과도하게 트래킹 이벤트를 보내는 것을 방지하였습니다.

:bug: ADD Accumulate Decorator for preventing multiple use-state tracking

---

release/scripts/startup/abler/object_control.py

object control 패널 기능들은 context.selected_objects만 확인하고 있어 context.object도 추가해주었습니다.
노션 문서 : https://www.notion.so/acon3d/Sentry-Look-At-Me-NoneType-66cb4cef62f546bd84c5722b43b17738

context.object도 if문에 추가

---

release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/lib/tracker/_get_ip.py
release/scripts/startup/abler/lib/tracker/_mixpanel.py
release/scripts/startup/abler/lib/tracker/_sentry.py
release/scripts/startup/abler/lib/tracker/_tracker.py

(이전 2.93버전에서 작업한 내용 cherry-pick으로 가져왔습니당)
get_ip 함수에서 `try : ip = get("https://api.ipify.org").text`로 ip를 받아오고 _mixpanel.py의 _enqueue_email_update 함수에 ip를 meta데이터에 심어주면 믹스패널에서 자동으로 국가별 트래킹을 해줍니닷!

믹스패널 국가별 트래킹

---

launcher_abler/AblerLauncher.py

런처 실행시 userpref.blend를 삭제해주고 있습니다.
해당 구문 삭제하는게 좋을지 고민하다 주석처리하고 설명 추가했습니다.
노션 문서 : https://www.notion.so/acon3d/3f16cfda4dfb47b78cdc57cf0580095d

런처 실행시 언어 설정 적용 에러

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/object_control.py

`ObjectAllSelectOperator` 를 추가하여, 키맵에서 기존에 사용되던 블렌더 내장 `object.select_all` 과 교체하였습니다.
<이슈>
keymap 파일 (`abler_defaults.py`) 에서 넣어주는 `properties` 를 오퍼레이터에서 사용하는 방법을 찾지 못해서, `invoke` 함수를 추가하여, 해당 함수에서 key event 별로 `action`을 나누고, `action` 에 따라 `execute` 시 동작을 분기하였습니다.

전체 선택 후 삭제 시 카메라와 Sun은 남기도록 만들기

---

release/scripts/startup/abler/camera_control.py

- 아래 영상과 같이 Background Image 토글이 꺼져있는 상황에서도 Background Image 추가가 가능함
https://user-images.githubusercontent.com/43770096/179885881-526d2048-5ca5-4c25-9c85-2ecb3be0bcf3.mov
- @JJong84  님의 QA로부터 인지됨
- background images 헤더 토글을 끄고 있는 상태에서 Add Images 버튼을 누릅니다.
- 잘 모르겠습니다.
https://user-images.githubusercontent.com/43770096/179886259-5ea97c91-5c07-4e83-86c0-e0b0f3f12a81.mov

배경 이미지 토글이 꺼져있는 상태에서도 이미지 추가가 가능한 문제

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/general.py
release/scripts/startup/bl_ui/space_topbar.py

믹스패널 트래킹을 위해 "최근 파일 열기"를 커스텀 오퍼레이터로 교체하였습니다.
기존 "최근 파일 열기" 기능과 최대한 디자인을 비슷하게 유지시켰습니다.
기존
이번 브랜치

최근 파일 열기를 커스텀 오퍼레이터로 교체

---

release/scripts/startup/abler/general.py

- 블렌더에서 좌측상단 메뉴의 File > Open 을 통해 파일을 열 때, 편집된 내용이 있다면 저장할 거냐고 물어보는 모달이 뜨지만, 에이블러에서는 뜨지 않습니다.
- 블렌더처럼 파일 오픈 시 이전 작업 내용을 저장할 것인지 물어보는 창이 띄워진 후 넘어가면 좋을 것 같습니다.
- 수정 사항 만들기 → File → Open → 열고 싶은 파일 클릭
- 수정 사항 만들기 → Open Recent → 열고 싶은 파일 클릭

파일 열기 / 최근 파일 열기 시 Save Remind 추가

---

release/scripts/startup/abler/face_control.py

- 다중 object 선택 시, object material 영역에 보여지는 material list 가 어떤 object 에 대한 material 인지 사용자가 인지할 수 있도록 한다.
- 현재 Blender 의 구현 상, 다중 object 선택시에도 선택된 object 들에 포함된 전체 Material 리스트가 보여지지 않고 있으며, 사용자는 이로 인해 혼동을 느낄 수 있음.
- 이러한 혼동을 해결하기 위해, Blender 에서는 object material 섹션 상단에 material list 를 표시할 object 정보를 breadcrumb 형식으로 제공하고 있으며, 이를 에이블러에 이식하여 사용자 인지 문제를 해결하고자 함.
- 현재 상태
- 전체 object 선택 시에도, Object material 에는 코니에 대한 material list만 출력됨
- 블렌더 패널에서 확인 시, 전체 선택을 하더라도, 가장 최근에 선택된 object 에 대한 material list 만 출력하고 있음을 확인
- 블렌더에서는 대신, 해당 object material list 가 어떤 object 의 material인지 확인할 수 있는 breadcrumb을 제공
- 개발 요청 사항
- Object Material 섹션 내에 어떠한 object 의 material list 를 출력하고 있는지 확인할 수 있는 breadcrumb 의 추가를 요청드립니다.
- 목적별 패널 구성에 의한 UI 순서 변경은 적용범위가 아닙니다.
- 해당 Section에 대해서만 확인해주세요.
| 간단 기획 내용 | 담당자 | 연관된 정책서 | …

현재 active object와 active material을 나타내주는 breadcrumb

---

release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/pref.py

노션 문서 : https://www.notion.so/acon3d/ABLER-b404afd77b0c4ec8ab4c581e85a29541

배경이미지 Custom Image 버튼 추가 및 UI 변경

---

release/scripts/startup/abler/general.py

[노션 링크](https://www.notion.so/acon3d/4c95cdda7e1f4144b767ca72e66e1fc7)
- 블렌더와 다르게, 에이블러 내에서
Save as, Open File (v.0.2.3)
Save as, Open File, Open Recent (ABLER/main)
동작 시 최근 파일 리스트가 갱신되고 있지 않습니다.
|  | ABLER (as-is) | BLENDER (to-be) | Custom Operator 사용 여부 |
| --- | --- | --- | --- |
| Open (Recent) File | X | O (리스트 최상단) | O |
| Open (Recent) File - 변경사항 있을 때 (모달 띄워질 때) | O | O (리스트 최상단) | O |
| Open Recent - File Not Found | X | O (리스트에서 삭제) | O |
| Save as | X | O (리스트 최상단) | O |
| 파일로 프로그램을 여는 경우 | O | O (리스트 최상단) | X |
- Save as, Open File (v.0.2.3)
Save as, Open File, Open Recent (ABLER/main) 동작 수행
- File → Open Recent 내의 파일들이 갱신되었는지 확인한다.
- 기존 블렌더의 동작을 저희 커스텀 오퍼레이터로 교체하면서 생긴 이슈 같습니다.
- bpy.wm.open_mainfile, bpy.wm.save_as_mainfile 에 True 를 추가하였습니다.
- delete_path_from_recent_files …

최근 파일 리스트 갱신 안되는 오류

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/face_control.py
release/scripts/startup/abler/lib/bloom.py

QA에서 나온 이슈 중 bloom의 property가 max값 이상으로 입력이 되는 에러가 발생하고 있습니다.
bloom의 property는 블렌더에 있는 scene.eevee의 property를 그대로 쓰고 있어서 오버라이딩을 하기 위해 ACON_prop으로 한번 감싸서 default, min, max값을 지정해줬습니다.
노션 문서 : https://www.notion.so/acon3d/Bloom-min-max-min-max-2fabf435e75046d3b5b3521383fe4a8d

[QA] bloom property ACON_prop으로 교체

---

release/scripts/startup/abler/face_control.py

- 윈도우11
- 0.2.4
- Object 가 하나도 선택되어있지 않은 상태
- Face Control > Object Material 확인
- 선택된 object가 없으나, object가 표시되는 상태
- selected object 를 바라보고 object가 선택되지 않았다면, object material list가 보이지 않아야 합니다.
- 사양서 : [https://docs.google.com/document/d/1OeMIcIQSIOOPD0BptuEcL7P9th75gkjpSaPSu0_Ce5E/edit](https://docs.google.com/document/d/1OeMIcIQSIOOPD0BptuEcL7P9th75gkjpSaPSu0_Ce5E/edit)
- 프로토타입 :
[https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FAcRvoHCr5Ga8Y1nmeo3QhV%2F%25EC%2597%2590%25EC%259D%25B4%25EB%25B8%2594%25EB%259F%25AC-%25EA%25B8%25B0%25ED%259A%258D%25EC%2584%259C-%25EB%25AA%25A8%25EC%259D%258C%3Fnode-id%3D391%253A4929](https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FAcRvoHCr5Ga8Y1nmeo3QhV%2F%25EC%2597%2590%25EC%259D% …

[0.2.4 QA] 선택된 object가 없을 시에도, material list가 노출됨

---

release/scripts/startup/abler/object_control.py

- macOS 환경 (이지만 Windows에서도 발생 확인)
- ABLER 0.2.4 버전
1. 선택된 Object가 없는 상태
- No selected object의 들여쓰기가 위의 Use State, Group Navigation의 헤더 맞지 않음
- 들여쓰기가 상위 토글과 맞아야 합니다
- 프로토타입과 사양서에는 해당 내용이 반영되어있지 않은 것으로 알고 있습니다. (cc. @콸 (최준영) 님)
- TBU

[0.2.4 QA] [Use State, Group Navigation] 들여쓰기 구현

---

release/scripts/startup/abler/general.py

[QA 링크 (노션)](https://www.notion.so/acon3d/Issue-07_-Open-Recent-Open-Recent-6a265e02d9f442ccb71e9dc06cd76d4b)
최근 파일 열기에서 없는 파일을 선택하면 최근 파일 리스트에서 해당 파일이 지워지는데, 그 후에 다른 프로젝트를 열면 지워졌던 파일이 다시 나타납니다.
- 저장 및 파일 열 때의 최근 파일 리스트 갱신은 블렌더의 내장 c 함수를 사용하지만, 해당 파일이 없어서 지우는 경우에는 에이블러의 커스텀 함수를 사용합니다.
- 블렌더의 내장 c 함수는 최근 파일 리스트를 변수 형태로 저장하고, 해당 리스트 변경이 필요할 때 **변수**와 **파일** 둘다 변경하도록 짜여있습니다.
- 에이블러의 커스텀 함수는 위 **변수**를 변경하지 않아서 File Not Found 후 다른 파일을 열면 에이블러의 변경사항이 반영되지 않는 것으로 보입니다.
- 최근 파일 수정하는 로직을 모두 블렌더 기본 동작이 아닌, 에이블러 내에서 동작하도록 변경하도록 하였습니다.
- 최근 파일 리스트는 최대 10개 유지되고, 제일 오래된 순으로 리스트에서 지워집니다. (실제 블렌더 동작을 참고하였습니다.)

[0.2.4 QA] 저장, 다른 이름으로 저장, 파일 열기 시 최근 파일 목록 갱신하는 함수 생성

---

release/scripts/startup/abler/lib/read_cookies.py

path_cookies_tutorial_guide 파일이 없을 때도 튜토리얼 가이드 실행되게끔 return값을 True로 돌렸습니당

[0.2.4 QA] 런처로 최초 실행 시 노출

---

release/scripts/startup/abler/credential_modal.py
release/scripts/startup/bl_operators/wm.py

[QA 이슈 링크](https://www.notion.so/acon3d/Issue-05_-Splash-Screen-Operator-Tooltip-undocumented-operator-454ec25791194698bf902a130b9b039d)
각 버튼에 대해 요청받은 툴팁은 다음과 같습니다.
`See ACON3D models!`
- 국문 : 에이콘3D 보러가기
- 영문 : Link to ACON3D
`Don't have an ACON3D account?`
- 국문 : 에이콘3D 회원가입
- 영문 : Sign up for ACON3D
Notice 항목
- 국문 : 에이블러 서비스 공지사항
- 영문 : ABLER Service Notice
- 공지사항 항목은 기존에 하던 방식대로 bl_description 을 추가했습니다.
- AnchorOperator 의 툴팁은, 워니님이 알려주신 description class method 를 이용해서 추가했습니다. 이 때 번역을 하기 위해 [pgettext](https://docs.blender.org/api/current/bpy.app.translations.html#bpy.app.translations.pgettext) 를 사용했습니다.

[Splash Screen] 일부 Operator 에 대해서 Tooltip이 정의되어있지 않아, (undocumented operator) 툴팁이 노출됨

---

release/scripts/startup/abler/general.py

파일 오픈 관련된 에러 메세지를 `self.report`에 넣어서 출력하도록 변경했습니다.
추가로 스듴님이 이전에 작업하신 파일 경로에 파일이 없는 경우 코드도 `self.report`에 합칠 수 있어서 삭제한 뒤, 워니님께서 작업해주신 파일이 없는 경우 최근 파일 목록에서 제거시키는 `update_recent_files`를 except에 넣었습니다.
노션 문서 : https://www.notion.so/acon3d/open-import-OSError-710d4ce21a4643bbaf4bf81a44de23d9

[0.2.4 QA] 파일 오픈 에러 메세지 출력

---

release/scripts/startup/abler/credential_modal.py

[QA 이슈 링크](https://www.notion.so/acon3d/Issue-04_-Show-Abler-Start-Splash-d0d936458268411cabe584df47cab862)
- modal 메소드는 여러 사용자 이벤트(클릭, 창전환 등)가 발생할 때마다 실행되는데, 
- 자동로그인이 되어있는 경우, 기존 코드의 if 문은 항상 통과될 수밖에 없기 때문에 스플래시가 닫히기 전에 튜토리얼 팝업이 뜨는 문제가 발생했습니다.
- 따라서, event.type 값이 명시적으로 좌클릭이어야 스플래시가 닫히게 수정해서, 스플래시가 닫히기 전에 튜토리얼 팝업이 뜨는 문제를 회피했습니다.
이렇게 수정했을 때 발생하는 부작용이 있는데,
- 기존에는 스플래시 스크린을 ESC 같은 키를 눌러서 닫는 것과 클릭해서 닫는 것에는 별 차이가 없었지만
- 수정 후에는
- 클릭을 해서 스플래시 화면을 닫았을 때는 튜토리얼 팝업이 바로 뜸
- ESC 같은 키를 눌러서 스플래시를 닫았을 때는 한 번 클릭을 해야 튜토리얼 팝업이 뜸
위와 같은 부작용이 생기지만, 애초에 스플래시 화면에 클릭을 하라는 문구가 포함되어있기 때문에 큰 문제가 되지 않을 것으로 판단했습니다.

[0.2.4 QA] 스플래시가 닫히기 전에 튜토리얼 팝업이 뜨는 문제 수정

---

release/scripts/startup/abler/general.py

파일 오픈에선 블렌더 내부에서 경로 없음, 파일 형식 등의 에러를 걸러줘서 self.report(str(e))로 에러 메세지를 자동으로 출력했었는데, import에서도 동일한 코드를 쓰니 번역이 안되는 문제가 있었습니다. 이는 파일 오픈에선 `BKE_reportf` 코드를 쓰지만 import에선 `PyErr_Format` 라는 파이썬 내장 코드를 써서 번역이 안되는거 같습니다.
때문에 import 에러 메세지는 `Fail to import blend file. Check filepath.`로 무조건 스트링으로 출력하게 변경했습니다.

[0.2.4 QA] import 에러 메세지 출력 

---

source/blender/editors/interface/interface.c

ACON3D/blender#102 에 대하여 논의 중 leading zero 자체를 오류로 보자는 방향으로 논의가 되어서 ACON3D/blender#71 까지 revert하기로 결정됨.
이슈 링크 : https://www.notion.so/acon3d/Issue-12-Input-Field-001-0-4cb03f010222462ebd6c6f8574502d16

Revert "숫자 앞에 0 표기 오류"

---

release/scripts/startup/abler/pref.py

`.blend1` 파일은 백업 기능을 가지고는 있지만, 대부분의 경우에서 사용되지 않고 용량을 두 배를 차지하게됨. 그리고 사용성에 이질감이나 뭔가 잘못되었다는 느낌을 줄 수 있기 때문에 관련 파일을 생성하지 않게함
관련 Notion 문서: [.blend1 파일이 생성되지 않게 Save Version 비활성](https://www.notion.so/acon3d/blend1-Save-Version-8f03c0a6a3ec414c9208108b9372fa85)
- userpref.py 에서 Save Version 관련 내용을 찾을 수 없음. (PreferencesFilePaths 포함)
```python
def init_setting(dummy):
prefs = bpy.context.preferences
prefs_paths = prefs.filepaths
...
prefs_paths.save_version = 0
```
- 파일 저장 시 `.blend1` 파일이 생성되지 않음
- Edif > Preferences > Save & Load > Save Version 에서 다른 값으로 설정하고 종료 or 저장 후 종료를 해도 다시 실행했을 때, Save Version = 0 으로 설정됨

[0.2.4 QA] .blend1 파일이 생성되지 않게 Save Version 비활성

---

release/scripts/startup/abler/general.py

[태스크 카드 링크 (노션)](https://www.notion.so/acon3d/Open-Recent-recent-files-txt-fd0f55895d1e4ebaac1c993943f08c91)
- 첫 설치 후, 혹은 recent-files.txt 를 삭제 한 후 최근 파일 리스트에 접근이 불가해집니다.
- 0.2.4 QA
- 에이블러를 처음 설치한다.
- 혹은 recent-files.txt 를 삭제한다.
- macOs
- `/Users/$USER/Library/Application Support/Blender/{version}/recent-files.txt`
- window
- `%USERPROFILE%/AppData/Roaming/Blender Foundation/Blender/{version}/recent-files.txt`
- 0.2.4 QA 이후로 생긴 것 같습니다.
- 매 저장, 파일 Open 시마다 recent-files.txt 를 체크해서 없으면 생성하도록 하였습니다.

[0.2.4 QA] 첫 설치 후, 혹은 recent-files.txt 삭제 후 정상적으로 최근 파일 리스트가 보이지 않는 문제

---

release/scripts/startup/abler/credential_modal.py

[관련 이슈 링크](https://www.notion.so/acon3d/Issue-04_-Show-Abler-Start-Splash-d0d936458268411cabe584df47cab862?d=2e38398e21b64fef944cfe89ff870465)
댓글 중에 "엔터키로 스플래시가 닫히지 않는다"는 제보가 들어와서 보니, 엔터키로 스플래시가 닫히게 하려면 "ENTER" 대신 "RET" 을 써야 했습니다 흑흑.. 왜 된다고 생각했던 거지
리뷰 & 테스트 부탁드립니다.

엔터키로 스플래시가 닫히지 않는 문제 수정

---

release/scripts/startup/abler/camera_control.py

사용하지 않는 이미지가 파일 내에 계속 쌓이는 버그가 있어서,
사용하지 않는 이미지를 삭제하는 로직을 배경이미지 추가/삭제 오퍼레이터에 추가하였습니다.

배경 이미지 추가/삭제/수정 시 기존 이미지를 삭제하는 로직 추가

---

release/scripts/startup/abler/credential_modal.py

sys.argv를 이용해서 .blend를 아규먼트로 여는지 (.blend 파일 더블 클릭해서 여는지) 확인하고, 그렇지 않다면 스플래시 스크린이 뜨지 않아도, 클릭을 하지 않아도 바로 Tutorial이 뜨도록 함 (Tutorial 여는 체크박스가 체크 되어있는 상황에서만)
- 윈도우11
- 0.2.4버전
- Show ABLER start 가 체크상태 (에이블러 실행 시 자동 튜토리얼 노출 상태)
- 블렌더 파일(file_open_test.blend)을 더블클릭하여 에이블러 실행
- 파일 오픈 시, 튜토리얼 팝업이 노출되지 않음
- 해당 화면에서 어느 곳이든 1회 클릭 시, 튜토리얼 팝업 노출됨 (클릭, 우클릭, 휠클릭, ESC, Enter 모두 동일)   
- show ABLER start = True 일 시, .blend파일을 더블클릭으로 오픈 시에도 동일하게 튜토리얼 팝업이 바로 노출되어야 합니다.
- Plan B : .blend 파일 더블클릭으로 오픈 시, 튜토리얼 팝업 노출되지 않음

.blend 파일을 열어도 바로 Tutorial 스플래시가 나올 수 있도록 수정함

---

source/blender/editors/interface/interface_handlers.c

UI 업데이트 시에 rnaProperty의 identifier가 password, password_shown, username 이면 undo stack에 쌓이지 않도록 수정

password를 입력했을 때 해당 내용이 그대로 undo history에 노출 되는 현상

---

release/scripts/startup/abler/general.py

실제 사용하는 부분의 내용과 맞지 않던
Acon3dImportPanel 의 이름과 idname 을 Import => General 로 변경하였습니다.
[노션 링크](https://www.notion.so/acon3d/Acon3dImportPanel-cad22d48952c4249bef31da9431a9a54)

Acon3dImportPanel 이름 변경

---

release/scripts/startup/abler/face_control.py

0.2.4에 추가된 active_material 표시 기능 중 active_material이 없는 경우 에러가 발생합니다.
에이블러 상에서 에러 재현은 못했지만 if문으로 확인 후 없으면 서프레스하도록 코드 추가했습니다.
노션 문서 : https://www.notion.so/acon3d/active_material-None-type-4a22f53d3fca4276ad307a2d8d792738

obj.active_material이 있는지 확인

---

release/scripts/startup/abler/general.py
release/scripts/startup/abler/import_external_files.py
release/scripts/startup/abler/lib/import_file.py

- 빈 문자열을 받아 파일 열기를 했을 때 에러 발생
- 센트리 오류
[[Sign In | Sentry](https://sentry.io/organizations/carpenstreet/issues/2785438622/?environment=production&project=6046815&query=is%3Aunresolved)](https://sentry.io/organizations/carpenstreet/issues/2785438622/?environment=production&project=6046815&query=is%3Aunresolved)
- 알앤디 개발셀
- 파일 창 열었을 때 빈 곳을 더블 클릭하면 발생
- 빈 문자열일 때 suppress하는 코드가 없어서 발생
- 동일한 현상이 [Import FBX]에도 발생하므로 같이 달아주면 될거 같습니다.
[https://acontainer.slack.com/archives/C02K1NPTV42/p1657785061394089](https://acontainer.slack.com/archives/C02K1NPTV42/p1657785061394089)
[https://github.com/ACON3D/blender/pull/57](https://github.com/ACON3D/blender/pull/57)

import시 File dialog에서 빈 곳을 클릭하면 뜨는 버그를 resolve

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py

[노션 링크](https://www.notion.so/acon3d/Warning-9ed3bc2335db4d129509b1430a3e8a32)
아래와 같은 오퍼레이터의 properties 를 키맵에서 삭제했고, 정상동작하는 것으로 보입니다.
- acon3d.render_full
- acon3d.render_quick
- acon3d.context_toggle
- file.execute
- object.transfer_mode
- acon3d.object_select_all

개발 시 뜨던 Warning 제거

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/image_adjustment.py
release/scripts/startup/abler/lib/materials/materials_handler.py

<img width="197" alt="스크린샷 2022-08-18 오후 7 57 58" src="https://user-images.githubusercontent.com/87409148/185379137-0f5b86e2-ace8-454a-9924-45f6b24fcfe3.png">
Color Management에 있던 Exposure, Gamma 토글을 custom_properties에 연결해 에이블러 Image Adjustment 패널 내 추가했습니다.
노션 문서 : https://www.notion.so/acon3d/Exposure-Gamma-6958b83530f04c22bb57558f32cb9343

Exposure, Gamma 토글 추가

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/pref.py
release/scripts/startup/abler/render_control.py

1. 렌더 토글에 `user_interface.transparent_checker_primary `프로퍼티를 그대로 가져와 row.prop으로 써서 배경색을 변경하도록 했습니다. 추가로 pref.py에 컬러 토글을 `"SQUARE_SV"`로 설정해주었습니다.
2. 그러나 프로퍼티를 직접 바꿔 배경색을 변경하면 다시 켰을 때 배경색이 저장되지 않는 문제가 발생했습니다.
그래서 배경색 값을 저장하는 ACON_prop의 커스텀 프로퍼티(`background_color`)를 만들어 row.prop으로 토글에 넣었습니다. 이렇게 되면 배경색을 기억해 껐다가 켜도 프로퍼티가 남아있습니다.
3. 하지만 껐다가 켰을 때 프로터티에 값은 남아있는데 에이블러를 켰을 때 바로 반영이 안되는 문제가 있었습니다. 
이는 이전에 겪었던 문제고 post_open의 커스텀 프로퍼티 값들을 받아와 업데이트 해주는 `change_and_reset_value()` 내에 Color 타입을 추가해주어 켤때마다 반영되도록 했습니다.
노션 문서 : https://www.notion.so/acon3d/0649a4860018414383d536f8e17cbf6f

뷰포트 배경색 변경

---

source/blender/editors/interface/interface_handlers.c

[슬랙](https://acontainer.slack.com/archives/C02K1NPTV42/p1661766293657939)
[태스크 카드](https://www.notion.so/acon3d/705e63e117e04ab0a77647804b823abb)
- 아웃라이너에서 레이어 이름을 변경하면, 앱이 강제 종료됩니다.
- but→rnaprop 이 NULL 일 때 위 이슈가 발생하는 것으로 판단되어 해당 부분에 NULL 이 아닐 때만 동작하도록 조건을 추가하였습니다.

레이어 이름 변경 시, 앱이 강제종료되는 현상 수정

---

release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/lib/import_file.py

[노션 링크](https://www.notion.so/acon3d/Open-Import-0016b6d59fa44838bd48b55502fd441e)
- 빈 문자열을 받아 파일 열기를 했을 때 발생하는 에러에서 오류 메시지가 현 상황을 제대로 설명하지 못함.
- background image import에서는 적용이 되어있지 않았음
- 아래 내용에서 지칭된 부분들에 대하여 빈 곳을 클릭하였을 시, 그 아래 그림과 같은 오류 메시지가 표출되도록 처리함.
- `File Open`,  `Import`, `Import FBX`, Background Image> `Custom Image`, `Default Image`

파일 다이얼로그에서 빈 공간 클릭 시 에러메시지 추가

---

release/scripts/startup/abler/general.py

[Notion](https://www.notion.so/acon3d/Import-1460fc44d04d4b6aad69e179fb3b84b6)
[Slack](https://acontainer.slack.com/archives/C02K1NPTV42/p1662536717842939) 논의 내용
- Import 관련 에러를 처리하는 중, 사용되지 않는 코드가 있어 삭제하였습니다.
- `general.py`에서 사용되지 않는 변수 `children_names`, `found` 관련 코드를 삭제했습니다.

ImportOperator에서 사용되지 않는 부분 삭제

---

release/scripts/startup/abler/lib/scenes.py

[노션 링크](https://www.notion.so/acon3d/Nonetype-a25d1c51174d4b11a9597f9f041b3ce4)
- 아웃라이너에서 View Camera를 지우고 씬을 추가하는 경우에 old_scene의 씬 카메라 정보가 없어서 Nonetype 에러가 나고 있었음

아웃라이너에서 카메라를 지워서 없을 때, 새로운 카메라를 만들어서 카메라뷰로 켜주는 로직 추가

---

release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py

- [[Import] 파일 오픈 후, 같은 파일 Import 하면 Layer 오류 발생](https://www.notion.so/acon3d/Import-Import-Layer-cb39914724cc410e9a5e83d50a0a0055)
- [[Import] 파일 오픈 후, 다른 파일 Import 하면 Layer0.001 레이어가 생기는 문제](https://www.notion.so/acon3d/Import-Import-Layer0-001-aa80454dc11c4321bfdad23d6b617227)
- [파일 오픈 후, 같은 .blend 파일을 import 했을 때 노출되는 에러 알림 번역 #20](https://github.com/ACON3D/blender-translations/pull/20)
- 에이블러에서 `.blend` 파일을 오픈하고, 경로와 이름이 같은 (`filepath`가 같은) 파일을 import 하면 중복 레이어와 오브젝트에 대해서 에러가 발생하고 있었습니다. 그래서, 같은 파일에 대해서는 에러 알림을 노출하는 것으로 수정하였습니다.
- 에이블러에서 `.blend` 파일을 오픈하고, 다른 파일을 import 하면 중복 레이어 (이름이 같은) 에 대해서 `.001` 과 같은 Blender 넘버링이 추가되고, 노출하지 않는 `Layer0.xxx` 이 레이어 패널에 노출됩니다. 그래서, 레이어 중복 처리를 해주었습니다.
분량이 많아서 Notion 문서로 확인하는 것이 좋습니다.
- 현재 열려 있는 파일의 `filepath` 와 import 에 사용되는 `filepath`를 비교함
- 현재 열려 …

파일 오픈 후, .blend 파일 import 에러 처리

---

release/scripts/startup/abler/render_control.py

[링크](https://www.notion.so/acon3d/1651602716624bd6b5f05a808e160329)
- self.render_queue가 있을때만 post_render 동작해야 하는데 not 구문을 넣음
- not 삭제..

self.render_queue가 있을 때만 post_render 작동

---

release/scripts/startup/abler/lib/version.py
release/scripts/startup/bl_operators/wm.py

[노션 카드](https://www.notion.so/acon3d/config-ini-splash-screen-8dc1947124294134b7d8333dc594de9d)
- config.ini와 splash screen의 버전정보가 일치하지 않을 수 있는 케이스가 있어서 테스트에 어려움이 있음

config.ini의 버전정보를 splash screen에서 보이도록 만들기

---

release/scripts/startup/abler/startup_flow.py

[이슈 링크](https://www.notion.so/acon3d/Issue-34_-Open-652d1e4ed5354107b831e01708186dac)
- 과거 버전 파일 Open 시, 팝업 내에 에이블러 업데이트 버튼이 출력됨
- [정책서](https://www.notion.so/acon3d/AB01_01_-d3ce15797ddf45af8b7e95d58b67fd2f)에 따르면 과거파일 Open 시에 뜨는 팝업에서는 에이블러 업데이트 버튼이 출력되면 안되므로, 해당 내용에 맞도록 Update 버튼을 없앰

과거 파일 Open 시에, Update Button이 출력되어서 정책서에 맞게 해당 버튼을 없앰.

---

release/scripts/startup/abler/render_control.py

[노션](https://www.notion.so/acon3d/Full-Line-Shadow-Render-Scene-56ef0a185af44bc9befd132810781685)
- Full/Line/Shadow Render 시에 Scene의 명칭이 변경되고 있습니다.
- 파일 넘버링 과정에서 qitem과 self.initial_scene이 바라보고 있는게 같은 context.scene임. → qitem이 업데이트 되면서 context.scene과 self.initial_scene이 같이 업데이트됨
- 퀵렌더에선 발생하지 않아 비교해보니 퀵렌더에선 qitem을 쓰지 않고 self.filepath로 바로 업데이트 하고 있음 → 퀵렌더 코드의 파일 넘버링을 대신 넣었더니 에러 없이 풀렌더 후 이름이 잘 나옴 → 중복되는 해당 코드 `check_file_numbering()` 함수로 묶기
- 쉐도우 렌더, 라인 렌더에선 scene.copy() 후 적용이 안돼서 현재 씬을 복사한 씬으로 돌려둠
- 추가로 on_render_finish에 `bpy.data.window_managers["WinMan"].ACON_prop.scene` 코드가 상속 후에도 중복되고 있어서 super().on_render_finish로 바꿔줌

Full/Line/Shadow Render 시에 원래의 Scene으로 변경

---

release/scripts/startup/abler/render_control.py

[링크](https://www.notion.so/acon3d/Hide-778d73982d184dfdb82751a38a161070)
- 뷰포트 색 함께 렌더하기 기능과 함께 오픈하도록 논의되어 해당 기능은 숨기기로 했습니다.
- render_control의 UI 코드 주석처리

뷰포트 색 변경 UI 숨기기

---

release/scripts/startup/abler/startup_flow.py

[추가 예정](URL) 
- 에이블러 버전이 낮을 때 발생하는 업데이트 팝업에서 Update ABLER를 실행하면 관리자 권한으로 런처가 실행됨
- 이 때, 에이블러가 정상적으로 종료되지 않는 문제가 있음.
- 에이블러 업데이트를 위해서 에이블러 종료가 필수기 때문에 이 문제를 수정함
- `subprocess.call(launcher, shell=True)` 을 `subprocess.Popen(launcher, shell=True)` 로 수정함
- `call()` 은 런처를 `blender.exe` 의 child process 로 실행하고 있어서 `bpy.ops.wm.quit_blend()` 를 실행하지 못하는 문제가 있었음.
- 그래서 `Popen()` 으로 런처를 실행해 독립적인 프로세스로 분리하고 정상적으로 에이블러가 종료되게 수정함.

업데이트 팝업에서 런처를 실행할 때 에이블러가 종료되지 않는 문제 수정

---

source/blender/depsgraph/intern/node/deg_node_component.cc

[노션 링크](https://www.notion.so/acon3d/crash-efa5bbfc45cc4833b0a2046cb6325716)
- ABLER v0.2.6
- Window 11
- Alienware 에서 발생 (~~나머지 환경에서 재현 안됨~~, 2022-09-22 18:17 하비님 컴퓨터 재현 추가)
- .blend 파일을 더블클릭하여 에이블러 실행
- 컨트롤 패널 > General > File Open, Menu > File > Open 시에도 동일하게 간헐적으로 발생
- 간헐적으로, 에이블러 클라이언트가 종료됩니다.
- op_node가 nullptr인 상황에서 EXCEPTION_ACCESS_VIOLATION이 나는것 같아서 op_node가 nullptr인지 아닌지 검사하는 로직을 추가함.
- 하지만 이 형태가 진짜 해당 이슈를 제거하는지는 테스트를 해보아야 알 수 있음.

op_node에서 Nullptr인데 접근을 해서 exception 발생 후 프로그램 종료되는 이슈

---

release/scripts/startup/abler/startup_flow.py

[태스트 카드 링크](https://www.notion.so/acon3d/File-Open-Show-Tutorial-Guide-cfbbfdde81264801b5e42b9d15e10e07)
이번에 수정된 시작 흐름때문에, 첫 실행 이후 다른 파일을 열었을 때 ACON_userInfo 메시가 생성되지 않았고, 그것을 참조하는 튜토리얼 가이드 측 코드에서 ACON_userInfo 를 찾지 못해 생긴 문제였습니다.
따라서, 첫 실행이든 그 이후에 열린 파일에서든 ACON_userInfo 메시가 생성되도록 만들어서 문제를 해결했습니다.

첫 실행 이후에 File Open 하면 Show Tutorial Guide가 작동하지 않는 현상

---

release/scripts/startup/bl_ui/space_topbar.py

[링크](https://www.notion.so/acon3d/Language-Korean-Menu-fd9fab5dfb8b4cc99b2850bf8b7ec0f6?d=53667b9e07d946b18803555627b926c2#f71109dd7836401db206b6f2bee6a81b)
- `...`이 “새 창이 뜨는 메뉴” 를 표시하기 위한 컨벤션이라 따라가기로 논의되었습니다.
- Open...으로 복구 및 번역 추가했습니다.

'Open...' 돌려놓기 + 번역 추가

---

release/scripts/startup/abler/lib/import_file.py

[개발 태스크 카드](https://www.notion.so/acon3d/File-View-6fd0e133b4c3451eb6920f6f4e30c18d)
[노션 쓰레드](https://acontainer.slack.com/archives/C02K1NPTV42/p1663909097037539)
- File View가 출력되는 모든 영역에서 더블 클릭 시, 아래의 메세지 출력하도록 변경
- 출력 메세지:
- File Select Error / No selected file.
- 파일 선택 오류 / 선택된 파일이 없습니다.
- File View의 빈곳 더블 클릭 시 출력되는 에러메시지를 변경하였습니다.
-` path.endswith("/") or path.endswith("\\") or path.endswith("//")` 조건과 `not os.path.isfile(path)` 조건이 다르지 않은 것으로 판단되어서 해당 부분의 조건을 `not os.path.isfile(path)` 만 남겼습니다.

File View의 빈곳 더블 클릭 시 출력되는 에러메시지 변경

---

release/scripts/startup/abler/startup_flow.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0051_-af0482022f7f4044855203a88ca2334d)
- 버전 없는 / 과거 버전의 에이블러(.blend)파일 실행
- 팝업 문구 확인
- 아래 문구로 수정했습니다

과거 버전의 에이블러 파일 실행 시, 팝업 문구가 잘못 입력되어있음

---

release/scripts/startup/abler/lib/version.py

[슬랙 스레드에서 논의한 기록](https://acontainer.slack.com/archives/C02K1NPTV42/p1663899347917989)
Github API rate limiting 때문에 서버 업데이트 체크 테스트를 할 수 없는 상황이라, CMS 쪽에 [해당 API 를 찔러서 1시간 동안 캐시해두고 내용을 그대로 반환](https://github.com/ACON3D/abler-cms/commit/756a4ec03bba7181f341a2a2d10ce01cd3ff7e8a) 하는 엔드포인트를 추가해서 문제를 회피합니다.

에이블러 업데이트 체크 URL 을 CMS 쪽으로 변경

---

release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/render_control.py

[개발 태스크 카드](https://www.notion.so/acon3d/2bb1ce82a5f34bb1a5c7a419098365f4)
[QA 이슈 카드 1](https://www.notion.so/acon3d/Issue-0040_-Full-Render-ee40c3eb2c1c4d699f1862d4dd8c91e8)
[QA 이슈 카드 2](https://www.notion.so/acon3d/Issue-0041_-977320d0405848d589230cb47aea3911)
프로젝트에 Scene 이 두 개 이상일 때, 현재 Scene 에 카메라가 없고, 다른 Scene 에 카메라가 한 개 이상 있는 상태에서
-  현재 Scene의 카메라를 지우고 render 를 호출하면 에러 발생
- create_scene 을 호출했을 떄 발생
1. 기본적으로 `View_Camera` 라는 이름으로 카메라를 만들도록 되어있으나, create_scene 에서 camera 가 없는 경우 `View Camera` 라는 이름으로 카메라를 만들고 있음
View Camera => View_Camera 로 수정하였습니다.
2. create_scene 의
`camera_object: Optional[Object] = bpy.data.objects.get("View_Camera")`
구문에서
-  다른 씬에 있는 카메라를 가져와서, 현재 씬의 View_Layer 에서 찾을 수 없어서 에러 발생
- View_Camera 라는 이름이 여러개 생기면 .001, .002 가 붙어서 제대로 가져오지 못하는 경우가 발생
위 두가지 오류가 있어서, …

카메라 삭제 후 렌더 및 씬 추가 에러

---

launcher_abler/AblerLauncher.py
launcher_abler/AblerLauncherUtils.py
launcher_abler/requirements.txt

Notion: [AblerLauncher에서 ABLER (및 Blender) 안전하게 종료하기](https://www.notion.so/acon3d/AblerLauncher-ABLER-Blender-bcfe9a25391445aa9c6585f5a15b7385)
- 파일 or 프로그램 버전 알림 팝업에서 Update ABLER 클릭하면, 해당 에이블러는 종료되고 런처는 정상적으로 실행됨
- 그러나, 다른 에이블러 클라이언트가 실행되어 있으면, Windows 에서는 켜져있는 프로그램에 접근할 수 없어 런처로 업데이트를 해도 정상적으로 업데이트가 되지 않는 문제가 있음
- 에이블러 런처에서 Update ABLER 클릭 시, 켜져있는 모든 에이블러 클라이언트들이 종료되어 정상적으로 업데이트가 진행되어야함
- 런처의 GitHub API URL을 CMS 주소로 변경
- [GitHub API URL](https://api.github.com/repos/ACON3D/blender/releases/latest) → [ABLER CMS API URL](https://cms.abler3d.biz/abler_update_info)
- 런처 유틸리티 모듈 (`AblerLauncherUtils.py`) 에 프로세스 개수를 세는 함수 `process_count()` 추가
- 실행되고 있는 프로세스 개수에 따라, 동작 분리
```python
def download() -> None:
...
if process_count("blender") == 0:
"Download ABLER"
else:
"프로그램 종료 QMessageBox"
``` …

AblerLauncher에서 ABLER (및 Blender) 안전하게 종료하기

---

release/scripts/startup/abler/startup_flow.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0052-09e13d23596148b78fec11112aca775f)
- 스플래시 스크린 상태에서 창 전환을 하면 튜토리얼 팝업이 스플래시 위로 올라옴
- 튜토리얼 팝업을 종료 시에 스플래시 화면이 남아있음
- 윈도우에서 Window deactivate 이벤트 발생할 시, 스플래시의 순서가 꼬이는 경우가 있어서 해당 경우에 False를 반환하도록 함.

스플래시 스크린이 출력 된 상태에서 창전환 시 튜토리얼 팝업이 스플래시 스크린 위로 올라오는 오류

---

release/scripts/startup/abler/startup_flow.py

[Reopen 된 QA 이슈 링크](https://www.notion.so/acon3d/Issue-0032_File-Open-Show-Tutorial-Guide-c150b50a210e4230aaedeafd29a4a69f)
- 튜토리얼 가이드를 띄울 때 ACON_userInfo 메시에 접근하는데, ACON_userInfo 는 start_authentication 에서 생성합니다.
- 그런데 "과거 파일" 을 여는 경우에, 실수로 start_authentication 을 실행하지 못해서 ACON_userInfo 메시가 생성되지 않습니다.
- 해당 경우에도 start_authentication 을 실행되도록 수정해서 해결했습니다.

과거 파일을 열었을 때 튜토리얼 가이드가 뜨지 않는 문제

---

release/scripts/startup/abler/lib/version.py

[슬랙 스레드 링크](https://acontainer.slack.com/archives/C02K1NPTV42/p1663814652493189)
- 기존에는 `ACON_metadata` 라는 이름의 text block 를 사용했기 때문에, Blender 내장 텍스트 에디터 (Shift+F11 로 접근) 에서 해당 항목이 보이고, 지울 수도 있는 상태였습니다.
- 여기에 기록되는 내용은 (많은 것들이 그렇긴 하지만) 미래에 출시될 에이블러에서 항상 안정적으로 접근할 수 있어야 하는 정보이기 때문에, 사용자가 실수로 지워버린다거나 하는 일이 가급적 발생하지 않는 구조이면 좋습니다.
- text block 이름이 `.` 으로 시작하면 텍스트 에디터 UI 에서는 보이지 않는다는 사실을 @JJong84 님이 알려주셔서, 사용자가 쉽게 접근하지 못하도록 해당 내용을 반영했습니다. (Outliner -> Data API 로 접근하면 여전히 보이긴 합니다만, 텍스트 에디터보다는 접근성이 훨씬 떨어집니다.)

메타데이터 저장용 text block 를 일반 UI 에서 보이지 않게 숨기기

---

release/scripts/startup/abler/lib/scenes.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0039_-244e83d84c21436a87f84cb38ef1173b)
- File open시에 간헐적으로, 에이블러 클라이언트가 종료됨
- 에이블러로 실행 시에 scene을 로드 하면서 가끔 GPU 연산이나 RAM이 꽉차서 뭔가 연산이 꼬일 경우가 있고, bpy.ops.object.Select_all()이 작동 하다가 크래시 나는 경우가 있는데 경우가 있음. 
- 해당 케이스에서 자료에 접근가능함이 그나마 보장 되어있도록 안전하게 케이스를 수정함.

에이블러 파일 더블클릭으로 오픈시, 간헐적으로 에이블러 클라이언트가 종료됨

---

launcher_abler/AblerLauncher.py
launcher_abler/AblerLauncherUtils.py
launcher_abler/UpdateLauncher.py

- [Issue #0053](https://www.notion.so/acon3d/Issue-0053-launch-abler-run-abler-launch-updater-89848080cbb24c11bf4b6761bcfd9f24)
- [네트워크 연결이 없으면 에이블러 런처에서 관련 메세지 띄워주기](https://www.notion.so/acon3d/e7f056db20af49a38bb84e9b11e04a6f)
- 네트워크가 연결되어 있지 않는 환경에서 에이블러 런처를 실행하면, Update Launcher 가 노출되며, 버튼 클릭 시에도 아무 반응이 없음.
- 따라서, 기획 요구 사항으로 해결 필요
- 네트워크 통신 테스트를 `bool` 타입 함수로 만듬
```python
def get_network_connection() -> bool:
"""네트워크 연결 상태를 bool 타입으로 return"""
try:
request = requests.get(set_url(), timeout=5)
return True
except (requests.ConnectionError, requests.Timeout) as exception:
return False
```
- 네트워크 통신이 `True` 이면 런처 정상 실행, `False` 이면 런처 네트워크 메세지 띄워주기
```python
class BlenderUpdater():
...
try:
if get_network_connection():
"런처 정상 실행"
else:
self.setup_execute_ui()
...
def setup_execute_ui(): …
```

네트워크 없이 런처를 실행할 때, 메세지 박스 출력

---

release/scripts/startup/abler/general.py
release/scripts/startup/abler/import_external_files.py
release/scripts/startup/abler/lib/import_file.py

[링크](https://www.notion.so/acon3d/importFBX-filepath-9f2e0fc5488a44879d227b086c134678)
- check_path 함수가 importFBX시에는 fbx 파일만 확인해야 합니다.
- check_path에 extension 파라미터를 추가해 .blend와 .fbx 다르게 확인하도록 변경했습니다.
- 추후 importSKP가 들어갈 때도 extension=".skp"로 구분해주면 될거 같습니다.

check_path시 extension 추가

---

launcher_abler/AblerLauncher.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0048-blendtemp-f9d282da4048461587c280d21967a33f)
- blendtemp 가 0.2.4 버전 파일 path에 blendertemp 파일이 다운로드됨
- 업데이트 완료 이후에 각 폴더 / zip파일 삭제
- launcher의 temp 폴더 위치를 AblerLauncher.exe의 위치로 정해줌

파일 더블클릭으로 에이블러 업데이트 시, 파일 경로에 blendtemp(다운로드 파일) 이 쓰여짐

---

release/scripts/startup/abler/lib/version.py
release/scripts/startup/abler/startup_flow.py

- [Issue #0055](https://www.notion.so/acon3d/Issue-0055_-Launcher-ABLER-f4fc30e5b7c44d52ae32a80bbede6e94)
- [에이블러 팝업으로 런처를 실행하면, 관리자 권한만 뜨고 런처가 실행되지 않는 문제](https://www.notion.so/acon3d/354fb0d62c304f8999943f36fc5881a1)
- 에이블러가 최신 버전보다 낮은 상태에서 과거 버전의 파일을 더블 클릭으로 실행하고, 업데이트 팝업에서 `ABLER 업데이트` 를 하면 다음 문제가 발생함.
- 에이블러 클라이언트는 정상적으로 종료됨.
- 에이블러 런처 실행을 위한 관리자 권한이 정상적으로 실행됨.
- 그러나, 권리자 권한에서 런처를 실행해도 런처 실행이 안됨.
- 에이블러에서 `subprocess.Popen` 으로 런처를 실행해주지만, 관리자 권한 팝업이 중간에 끼어 있어 런처 실행을 위한 작업 중에 에이블러가 종료되어 런처를 실행하지 못하는 것으로 추정됨.
- `subprocess.Popen` 으로 런처를 실행하고 에이블러를 바로 종료하지 말고, 런처 프로세스인 `AblerLauncher.exe` 를 확인할 때까지 에이블러 종료를 기다리기
```python
class Acon3dUpdateAblerOperator(bpy.types.Operator):
...
def execute(self, context):
subprocess.Popen("런처 경로", shell=True)
if "Windows":
while not (proc_count := …
```

에이블러에서 런처 프로세스를 확인하고 에이블러 종료하기

---

release/scripts/startup/abler/pref.py

- [Issue 0039](https://www.notion.so/acon3d/Issue-0039_-244e83d84c21436a87f84cb38ef1173b)
- [Issue 0058](https://www.notion.so/acon3d/Issue-0058-fd84882296d24fd7b46808e37679dc47)
- 파일 오픈 시 load_post 핸들러에서 Scene 데이터에 접근하다가 크래시 나는 문제를 회피하는 수정사항을 적용했습니다.
- 시간 인자를 생략한 bpy.app.timers.register 를 호출하면 이벤트 핸들러 바로 다음 틱에 실행되어 지연을 최소화하면서도, 필요한 초기화 이후에 실행되기를 기대하고 작성했습니다.
- 경고: 이 변경사항이 어떤 부작용을 일으킬 수 있는지 검증되지 않았습니다.

파일 오픈 시 때때로 크래시 나는 문제 회피

---

release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/import_external_files.py
release/scripts/startup/abler/lib/import_file.py

[개발 태스크](https://www.notion.so/acon3d/04e4f4455a3d4b1aa0bd7c15cc0b6098)
- 배경 이미지 선택 시 check_path의 파라미터가 없어서 에러가 발생하고 있습니다.
- check_path 와 동일한 역할을 하던 is_valid_extension 함수를 지우고, check_path 가 여러개의 extension 을 처리할 수 있도록 변경하였습니다.
-  이에 맞게 파라미터명도 accepted 로 변경하였습니다.

배경이미지 선택 시 에러 발생

---

release/scripts/startup/abler/startup_flow.py

[링크](URL)
작성 예정
- 에이블러 팝업 업데이트에서 `Update ABLER`를 하면 런처 실행을 위한 관리자 권한 팝업이 실행됨
- 관리자 권한 팝업에서 "아니오" 선택하면 프로세스를 계속 `while`로 탐색하고 있어 에이블러가 멈춤
- 런처 실행 여부를 `bool` 타입으로 정의하고, 에이블러에서 런처의 실행을 `Popen.poll()`로 탐색함

에이블러 업데이트 팝업 결과에 따라 에이블러 멈추는 문제 수정

---

release/datafiles/userdef/userdef_default_theme.c
release/scripts/startup/abler/pref.py

[기획 티켓 링크](https://www.notion.so/acon3d/Object-Control-f619ee9458c345ad9785f792c02567ad)
- 오브젝트 이동을 할 때 상대적 위치와 거리감을 확인할 수 있는 플레인과 그리드를 열어주는 것이 사용상에 편리함
- 참고 : [220812, 220817 3D툴 리서치 결과 ](https://www.notion.so/220812-220817-3D-31a12a043d174dce83c8235254fd5c5c)
- 가능 여부 판단이 우선
- depsgraph_update_post 핸들러에 floor과 grid를 켜고 끄는 기능을 붙여서 원하는 기능이 구현될 수 있도록 함.
- grid의 기본 컬러를 #8f8f8f로 바꿈 (기획 내용에 있음)
https://user-images.githubusercontent.com/43770096/190949391-ea6ef4d1-4639-4e8e-b4fd-e343045a41b1.mov

selected object가 있을 시에, 축 + 대지가 보이도록 하는 기능을 추가함.

---

release/scripts/startup/abler/lib/scenes.py

https://www.notion.so/acon3d/Deselect-762f3b0671854341969b2d4f00abef4d
- scene을 바꿀 때 load_scene()내의 refresh_look_at_me()내의 `bpy.ops.object.select_all(action=”DESELECT”)`에서 오류가 발생.
- select_all 함수는 EDIT_MODE에서 실행이 안됨
- OBJECT_MODE로 무조건 설정하는 코드 추가

씬 전환시 EDIT_MODE에서 런타임에러 발생하는 문제 

---

release/scripts/startup/abler/lib/scenes.py

[링크](https://github.com/ACON3D/blender/pull/176)
- 선택된 오브젝트가 없을 때 Object 모드로 설정하면 에러가 발생했습니다.
- 이전 브랜치에서 deselect_mode 를 
```
try:
if context.selected_objects:
for obj in context.selected_objects:
obj.select_set(False)
```
로 변경해 Object 모드 설정을 조건문 안에 넣기 위해 Revert 하고 다시 PR을 올렸습니다.
- 조건문 안에 object 모드로 설정하는 코드 추가했습니다.

[re-PR] EDIT_Mode에서 씬 전환시 런타임에러 발생하는 문제

---

release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/pref.py
release/scripts/startup/bl_ui/space_view3d.py

[오브젝트 면을 기준으로 스냅 기능 (Snap) 활성 및 헤더에서 사용되지 않는 기능 삭제](https://www.notion.so/acon3d/Snap-7ad354cfc4184853908ffe996cc9582c)
- 에이블러 내에서 Import 등을 통해서 여러 모델을 다룰 때, 모델끼리 표면에 snap 하는 기능이 필요함
- Blender 내에서 `Face Snap` 기능을 이미 제공하고 있어 해당 기능을 활용할 예정
- 해당 기능을 사용하기 위해서 상단바 또한 `Show` 로 열어야함
- 상단 기능 바 `Header` 를 표시함
- `Snap` 기능을 활성화하고 `Face` 로 적용
- Snap To 기능을 제외한 나머지 기능 숨기기 (상세 항목은 노션 문서)

오브젝트 면을 기준으로 스냅 기능 활성 및 헤더에서 사용되지 않는 기능 삭제

---

release/scripts/startup/abler/general_tab/general.py

[링크](https://www.notion.so/acon3d/Import-a64484b2a5454e5c9634377a77230c13)
- Import 기능 사용 시 현재 씬에만 레이어가 추가되고, 다른 씬에는 추가되지 않는 에러 발생
- ImportFBX에도 동일하게 발생
- l_exclude 등록할 때 for문으로 모든 씬에 추가해줌
- ImportFBX에도 동일한 작업을 해줌

Import 기능 사용 시 현재 씬에만 레이어가 추가되고, 다른 씬에는 추가되지 않는 에러

---

release/scripts/startup/abler/__init__.py
release/scripts/startup/abler/scene_tab/object_control.py

[링크](https://www.notion.so/acon3d/Object-Control-d2706235c0334950a70e88081f65333c)
- Object Control 패널 Scene 탭 하위로 옮김
- 기획서 상 Use State 제거
- 파일 이동 및 `bl_options = {"DEFAULT_CLOSED"}` 구문 삭제
- Use State 주석처리

Object Control 위치 수정

---

release/scripts/startup/abler/lib/layers.py

[링크](https://www.notion.so/acon3d/Scene-Scene-l_exclude-d422200fa53d474395abacf5f0d39920)
- 씬마다 레이어 갯수(l_exclude)가 달라 씬 전환시 handle_layer_visibility_on_scene_change 과정에서 에러 발생
- 이전 씬의 l_exclude의 i가 새 씬의 l_exclude 총 갯수보다 넘어갈 때 처리하지 않고 패스하도록 코드 추가했습니다.

Scene 변경 시 Scene 마다 l_exclude 갯수가 다를 때 발생하는 에러

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/pref.py
release/scripts/startup/bl_ui/space_toolsystem_toolbar.py

[툴바를 기본으로 표시하고 사용하지 않는 기능 정리하기](https://www.notion.so/acon3d/78532cb7a0eb458ebcafdad50a2291ff)
- 많은 디자인 툴에서 기본 Toolbar가 보여지는 상태로 제공되는 경우가 많고, 사용자들에게도 사용성이 더 좋을 것으로 예상됨
- 하지만, 툴바 기능 중에서 필요 없는 기능이나 제대로 작동하지 않는 기능이 있어서 관련 기능을 툴바에서 제외함.
- Toolbar가 보이는 것을 기본값으로 설정
- Toolbar에서 사용하지 않는 기능 제거
- `General` > `Toggle Toolbar` 삭제
- ABLER 사이드바 UI 에서만 삭제하고 관련 기능은 일단 남겨둠
- Toggle Toolbar 단축기 `T` 키 삭제
Toolbar가 보여지면 기존의 카메라 영역 (빨간 라인) 의 비율이 살짝 달라지면서 카메라 영역 바깥으로 여백이 생김

툴바를 기본으로 표시하고 사용하지 않는 기능 정리하기

---

release/scripts/startup/abler/pref.py

- #141에 같은 부분이 있고, black 처리를 같이 해줬음
[[Notion] 태스크 카드](https://www.notion.so/acon3d/pref-py-ACON3D-9718e7bb8516440b89f015b8862f9ede)
[[Sentry] 에러 링크](https://sentry.io/organizations/carpenstreet/issues/3652063572/?project=6046815&referrer=slack)
- `.blend` 파일의 화면 속성에 `"ACON3D"` 가 없는 상태에서 파일을 오픈할 때 발생하는 것으로 보임
- 직접 화면 이름을 수정하는 방법 말고 다른 재현 방법을 당장 찾을 수 없어 Sentry에서 Resolve 처리함
- `"ACON3D"` 라는 이름의 스크린이 없는 상태에서 `"ACON3D"` 라는 스크린이 접근
```python
def hide_header(dummy):
bpy.data.screens["ACON3D"].areas[0].spaces[0].show_region_header = False
```
- Screen에서 `ACON3D` 가 있을 때만 하위 속성 탐색
```python
def hide_header(dummy):
bpy.data.screens["ACON3D"].areas[0].spaces[0].show_region_header = False
if (
"ACON3D" in bpy.data.screens.keys()
and len(bpy.data.screens["ACON3D"].areas) > 0
and …
```

Screen에 ACON3D가 있을때만 내부 area 탐색하기

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/shadow.py
release/scripts/startup/abler/style_tab/styles_control.py

[Shadow / Shading 한꺼번에 끄는 prop 추가](https://www.notion.so/acon3d/Shadow-Shading-prop-f2f91c63cc7841868b6f8662fdc9057a)
- Shadow / Shading 한꺼번에 끄는 토글이 아래 `Shadow / Shading` Subpanel의 헤더에 들어가도록 기획됨
- 그러나 해당 토글이 존재하지 않음
- Custom Properties에 Shadow / Shading 을 한번에 토글할 수 있는 `toggle_shadow_shading` (`BoolProperty`) 속성 추가
- 이 속성 업데이트를 위해서 `abler` > `lib` > `shadow.py` 내부에 `toggle_shadow_shading` 함수 생성
- `bpy.types.Panel` 의 Classmethod `poll` 을 활용해서 toggle_shadow_shading 내부의 subpanel `ShadingPanel` 도 끌 수 있도록 업데이트
- Shadow / Shading 토글 업데이트 함수 내부에서 On/Off 결과에 따라 각 토글의 상태를 업데이트함
```python
def toggle_shadow_shading(self, context: Context) -> None:
prop = context.scene.ACON_prop
prop.toggle_shadow = True if prop.toggle_shadow_shading else False
prop.toggle_toon_face = True if …
```

Shadow / Shading 한꺼번에 on/off 하는 속성 추가

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/scene_tab/scene_control.py

[링크](URL)
- 개선된 Scene UI에서 씬 항목을 더블클릭으로 씬 이름 변경이 가능하게 기능 추가

개선된 Scene UI에서 항목 더블클릭으로 씬 이름 변경

---

release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/scenes.py

[링크](https://www.notion.so/acon3d/View_Camera-f1779444abb84a9e834f3fd3185a5a3d)
- 에이블러 뷰포트에서 카메라 오브젝트가 선택 가능함
- 파일 열 때 load_scene이 실행되므로 pref에서 따로 해줄 필요 X
- load_scene 이후에 추가로 카메라 생성할 때 선택될 수 있으므로

View_Camera 가 선택 가능한 에러

---

release/scripts/startup/abler/custom_properties.py

(참고) 실수로 blender-translation 레포에다가는 메인에 바로 푸시해버렸습니다... revert 하느니 그냥 냅두기로.. 조심하겠습니다...
[노션 태스크 카드](https://www.notion.so/acon3d/Edges-Line-4ea3d5ff21ba4f788b2f3030c45c3121)
- 유저들에게 edge 보다 익숙한 line으로 기능 명칭을 변경
- 에이블러 내에서 단일 기능에 대한 일관된 경험 제공
- 기존에 Edges라고 표기되어있던 것을 Line으로 변경

edge를 line으로 수정

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/addons.py
release/scripts/startup/abler/lib/locales.py
release/scripts/startup/abler/pref.py
release/scripts/startup/bl_operators/wm.py
release/scripts/startup/bl_ui/space_topbar.py

[태스크 카드](https://www.notion.so/acon3d/92196c8f7ef64e258d33666bdf31a9a1)
[에이블러 I.A.](https://docs.google.com/spreadsheets/d/1ClMV5ObLBfgqiRhaz3yLiViSret5GcYqU-k_vdvSj_c/edit#gid=1235797135)
- 현재 에이블러 내에서 제공하지 않는 기능이 많아서 필요 없는 기능들을 정리할 필요가 있음.
- 메뉴 항목 삭제
- 에이블러 I.A. 기준으로 삭제함
- 메뉴 항목 추가
- Import 기능은 addons 설정이 포함되어 있어, 필요한 Import 기능 메뉴를 따로 추가함
- Manul 및 Support 링크를 에이블러 링크로 변경
- 나중에 `Import` 기능이 완성되면 오퍼레이터를 알맞게 연결하는 작업이 필요함.

에이블러 메뉴 내 에이블러 미필요 기능 비활성화

---

release/scripts/startup/abler/lib/tracker/_tracker.py

[노션 태스크 카드](https://www.notion.so/acon3d/Mixpanel-Import-a425920515e5428b9e558029a51f7945)
- 같은 .blend 파일을 Import 했을 때, 믹스패널 로그가 제대로 찍히지 않음
- Enum 의 value 값을 받아올 수 있도록 수정한다.

같은 .blend 파일을 Import 실패했을 때 믹스패널 로그가 찍히지 않던 문제 수정

---

release/scripts/startup/abler/startup_flow.py

[blender-translation PR](https://github.com/ACON3D/blender-translations/pull/31)
[노션 태스크 카드](https://www.notion.so/acon3d/8172d057a3f94597993fd366d1969ff1)
- 로그인 실패했을 때, 오입력인 경우와 접속 제한인 경우를 구분해야함
- 로그인 여러 번 실패 후 접속 제한인 경우일 때 보여주는 메시지를 변경
- 로그인 에러 체크하는 조건 변

로그인 여러 번 실패 후 접속 제한인 경우 메시지 변경

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/materials/materials_setup.py
release/scripts/startup/abler/lib/scenes.py

[링크](https://www.notion.so/acon3d/default-516d52a031654335a67fba0e582b3f0a)
- 프로퍼티 중 default 값 변경 요청 PR입니다.
- `create_scene`에서 old_scene에 카메라 없을 때 카메라 생성 시 lens 43mm 적용
- `make_sure_camera_exists`에서 카메라 없을 때 카메라 생성 시 lens 43mm 적용
- ImportSKP가 transparent 다르게 나오는 이유 : [Transparent 코드 분석](https://www.notion.so/Transparent-c47df7721b2248599df172c9e8566e96)

Default 값 변경

---

release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/scenes.py

[링크](https://www.notion.so/acon3d/make_sure_camera_exists-c0b68a7fb9d64f5ea56a38601735258d)
- make_sure_camera_exists에서 카메라가 위치, 방향이 다른 에러 발생
-  create_scene() 내 카메라 생성 조건을 `make_camera()` 함수로 빼서 make_sure_camera_exists()에도 똑같이 넣어줌
-  location, rotation 값만 바꾸는 것보다 create_scene()과 동일하게 해야 헷갈리지 않을 거 같음
- 업데이트 된 startup.blend의 bpy.context.scene.camera.rotation_euler이 위의 값이 아닌 (1.5707963705062866, 0.0, -3.7000980377197266)인 radians로 나타내기 힘든 값이라 startup.blend의 rotation_euler만 `(radians(90), radians(0), radians(-212))`로 변경한 뒤 업데이트 해줌

make_sure_camera_exists에서 카메라가 위치, 방향이 다른 에러

---

release/scripts/startup/abler/general_tab/general.py

[링크](https://www.notion.so/acon3d/Import-file-extension-a3df542a9bae419888e4a93623d88235)
- Import Blender, FBX, SKP 3개의 오퍼레이터를 감싸는 상위 클래스를 만들어 파일 확장자에 따라 각각의 오퍼레이터 실행.

Import시 file extension에 따라서 교통정리

---

release/scripts/startup/abler/export_tab/export_control.py
release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/bl_operators/wm.py
source/blender/editors/include/UI_interface.h
source/blender/editors/interface/interface_templates.c
source/blender/editors/space_view3d/space_view3d.c
source/blender/makesrna/intern/rna_ui_api.c
source/blender/makesrna/intern/rna_wm_api.c
source/blender/windowmanager/intern/wm_operators.c
source/blender/windowmanager/intern/wm_splash_screen.c
source/blender/windowmanager/wm.h

[태스크 카드](https://www.notion.so/acon3d/328b595e2570421d8aabadead6e5496d)
- 사이드바에 렌더 프로그레스바와 관련 UI 를 추가함
- C
- stop render operator : 현재 진행되고 있는 렌더를 멈추는 오퍼레이터 추가
- `get_progress` : 현재 렌더의 진행상황을 반환하는 함수 추가
- `template_progress_bar` :  프로그레스바를 그려주는 함수 추가
- `view3d_buttons_region_listener` : ND_JOB 이벤트의 경우에도 다시 그리도록 수정
- python
- 렌더링에 쓰일 `progress_prop` 을 window_manager 에 추가
- `export_panel` 에 `draw_progress` 함수 추가

실시간으로 변하는 프로그레스 바 팝업 구현

---

release/scripts/startup/abler/lib/materials/materials_handler.py

[Active object가 없을 때 재질 속성에 접근하는 문제](https://www.notion.so/acon3d/Active-object-NoneType-10aa978fcc604f2da3e99327bb4144b2)
- Active object가 NoneType 이면 재질을 가져올 수 없어서 SKP Importer 과정에서 에러가 발생하고 있었음
- `context.active_object` 가 있을 때만 `material_slots` 를 가져올 수 있도록 변경

Active object가 없을 때 재질 속성에 접근하는 문제

---

release/scripts/startup/abler/lib/objects.py

[논의 링크](https://acontainer.slack.com/archives/C02K1NPTV42/p1667972995587609)
```
def toggle_constraint_to_camera(self, context):
obj = context.object
if obj.ACON_prop.constraint_to_camera_rotation_z:
tracker.look_at_me()
cameras.make_sure_camera_exists()
set_constraint_to_camera_by_object(obj, context)
```
- context.object가 없을 경우 생기는 오류로, 방어코드 작성이 필요함.
- obj에 if문과 바다코끼리를 사용해서 필터링함.

context.object가 없을 경우 update 함수가 돌아가지 않는 경우에 대한 방어코드 작성

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/lib/tracker/_tracker.py

[믹스패널 렌더 고도화 작업](https://www.notion.so/acon3d/37ec9fa8a570467daffb8b572156a5ff)
- 고품질 렌더 하위에 속하는 각각의 렌더 track 함수는 일단 유지
- 각 렌더 track 함수에서 믹스패널에 보낼 때 다음 사항 추가
- 파일 경로
- 씬 이름
- 소요시간
- 각 렌더 소요 시간의 합을 고품질 렌더의 소요 시간으로 일단 봐도 될 것 같음
- 데이터 정리는 믹스패널에서 해보기
- 현재 render operator를 실행하면 바로 tracker 함수가 실행되고 있음. 그래서 렌더가 완료되기 전에 데이터가 넘어가서, 렌더가 성공했는지 아닌지 제대로 확인하지 못하는 문제가 있음.
[https://acontainer.slack.com/archives/C01K142MCNS/p1667977988266589](https://acontainer.slack.com/archives/C01K142MCNS/p1667977988266589)
- 유저명으로 고유성을 가질 수 있는지 확인 필요
- 파일명만 남기면 고유성을 잃을 수 있음

믹스패널 렌더 고도화 작업

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/startup_flow.py

[링크](https://www.notion.so/acon3d/661ed2130d2d4371ae9934662261fe6b)
- 실제로 튜토리얼 가이드 버튼을 눌렀을 때만 믹스패널에 출력
- startup_flow.py에서 `acon3d.tutorial_guide_popup` 를 실행함
- `acon3d.tutorial_guide_popup` → `bpy.ops.wm.splash_tutorial_1("INVOKE_DEFAULT")` 로 직접 실행해 믹스패널 거치지 않는걸로 수정

튜토리얼 가이드 믹스패널 추가

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py

[태스크 카드](https://www.notion.so/acon3d/skp-fbx-import-44f09fdfa8bd4e0f84007c52be324d3e)
- Import SKP 애드온(io_skp) 켜주기 추가
- skp와 fbx에 대해서 애드온을 항상 켜주는 함수를 AconImportHelper에 추가함
- 더 효율적인 코드를 위해 서순을 살짝 바꿔줌

skp와 fbx import 애드온 항상 켜주는 내용 추가

---

release/scripts/startup/abler/export_tab/export_control.py
release/scripts/startup/abler/export_tab/render_control.py

[태스크 카드 링크](https://www.notion.so/acon3d/bbc46458ba3941bca1a7f01f84fa4e6b)
- 사양서와 현 렌더 모달 및 렌더 패널이 맞지 않는 내용이 있음
- HQ 렌더 모달 우측에 경고 문구를 추가했습니다
- 씬별 프로그레스의 제목-바 간격을 줄였습니다

렌더 프로그레스 사양서에 맞게 수정

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/bloom.py
release/scripts/startup/abler/style_tab/styles_control.py

[링크](https://www.notion.so/acon3d/Sunlight-Bloom-29e3f2c4bfe14c09ba648d77243aaf96)
- Sunlight 토글 해제 시 토글 하위 항목이 그대로 노출됨
- Bloom 토글 해제 시에도 동일한 현상 발생
- (+) bloom 내 bloom_color 프로퍼티가 custom_properties가 아닌 문제도 발견

Sunlight, Bloom 토글 해제 시 패널 닫히지 않는 문제

---

release/scripts/startup/abler/pref.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0070-Object-Control-fdfa8e39cefa45f4b5838af08172e063)
- 선택 오브젝트가 있어도 오브젝트 컨트롤 그리드가 노출되지 않음
- `depsgraph_update_post` 핸들러에서 사용하는 `grid_on_when_selected` 함수에 `@persistent` 데코레이터가 왠지 모르게 빠져있었음.

Object Control 그리드가 노출되지 않는 문제

---

release/scripts/startup/abler/camera_tab/background_control.py

[이슈 링크](https://www.notion.so/acon3d/Camera-UI-17b104bab78d405b813d9a9bf94a914a)
- 카메라 탭은 크게 Camera Control과 Background로 구성, Camera Control 하위에는 Focal Length 와 Dof, Background 하위에는 Background Images와 Background Color가 그루핑 되어있음
- 따라서 Background 와 Background Images는 분리 필요
- background 패널이 사양서와 살짝 다른 부분이 있어서 패널을 분리하고 naming을 추가함

Camera 탭 UI가 기획된 내용과 다른 부분

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/read_cookies.py
release/scripts/startup/abler/lib/user_info.py
release/scripts/startup/abler/operators.py
release/scripts/startup/abler/startup_flow.py

[태스크 카드 링크](https://www.notion.so/acon3d/General-New-Tutorial-guide-Python-error-091fa626469742b5a79e114b7235bd46)
- 튜토리얼 가이드 팝업과 로그아웃 기능 실행시에 ACON_userInfo 메시를 찾지 못해서 발생하는 문제를 해결했습니다.
- ACON_userInfo 생성 및 초기화를 하는 함수를 따로 빼고, 필요한 곳에서 재사용하도록 했습니다.

두 번째 창부터 ACON_userInfo 메시가 없어서 에러가 발생하는 문제

---

release/scripts/startup/abler/operators.py

[이슈 카드](https://www.notion.so/acon3d/Issue-0078-2-c4450052af9a4eafbd889d148f324012)
[태스크 카드](https://www.notion.so/acon3d/2-d0deca81cba347ae8526c30981a2949d)
- 로그 아웃 후 로그인 스플래시 모달이 두 개 보이는 현상
- `bpy.ops.wm.splash("INVOKE_DEFAULT")` 이 두 번 불러지고 있어서 `Acon3dLogoutOperator.execute`에서 삭제

스플래시 스크린이 2개 뜨는 문제

---

source/blender/makesrna/intern/rna_camera.c

[카메라 속성 UI 및 입력값 범위 조정](https://www.notion.so/acon3d/UI-d4978c40495746858306bef81079b80d)
- DOF 속성 (Focus Distance, F-stop) 의 UI 및 입력 설정값 범위가 사양서와 다름
- 번역 작업 후 merge
- [카메라 속성 UI 및 입력값 범위 조정 번역 #36](https://github.com/ACON3D/blender-translations/pull/36#pullrequestreview-1178826307)
진행 상황 및 조치
- `rna_camera.c` 에 DOF 관련 UI 및 입력 범위가 정의되어 있음.
- F-stop
```c
prop = RNA_def_property(srna, "aperture_fstop", PROP_FLOAT, PROP_NONE);
RNA_def_property_range(prop, 0.0f, 128.0f);
RNA_def_property_ui_range(prop, 0.0f, 5.0f, 10, 1);
```
- Focus Distance
```c
prop = RNA_def_property(srna, "focus_distance", PROP_FLOAT, PROP_DISTANCE);
RNA_def_property_range(prop, 1.0f, 50.0f);
RNA_def_property_ui_range(prop, 1.0f, 100.0f, 1, 2);
```

카메라 속성 UI 및 입력값 범위 조정

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py

[링크](https://www.notion.so/acon3d/display-mode-6063513ddd26417fa881fb5fd5e7a04b)
- 한번도 Background Default Image를 실행하지 않고 Blender File View Layer를 실행하면 Display Mode가 Vertical List 로 출력 됨.
- 한번이라도 Background default image 파일 레이어를 연 상태라면 이후에 어디에서  Blender File View Layer를 실행해도 Display Mode가  thumbnail view로 출력됨.

파일 뷰어의 display mode 차이나는 에러

---

release/scripts/startup/abler/export_tab/export_control.py
release/scripts/startup/abler/scene_tab/scene_control.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0073-Scene-1a579557a67a429081ccaf00a220cf3a)
- 윈도우 11
- 에이블러 0.2.6 (11/14 빌드)
- TC번호: abler_Scene_UI_03&04&05
- 추가 Scene 생성 후 **Scene 탭과 Export 탭 모두**
- 생성 순서대로 Scene이 정렬 되어 있음
- 내림차순으로 정렬되어 있어야 함
```python
class SCENE_UL_List(bpy.types.UIList):
def __init__(self):
super().__init__()
self.use_filter_sort_reverse = True
def draw_item(
self, context, layout, data, item, icon, active_data, active_propname
):
if self.layout_type in {"DEFAULT", "COMPACT"}:
row = layout.row()
row.prop(item, "name", text="", emboss=False)
```

 Scene 생성 시 씬이름이 자동으로 내림차순으로 정렬되지 않음

---

release/scripts/startup/abler/export_tab/render_control.py

[이슈 카드](https://www.notion.so/acon3d/Issue-0086-bd633065d9b54f48872e4d4d5343158d)
[태스크 카드](https://www.notion.so/acon3d/6e03c0e18e5140a197922b439407e61c)
- 스닙 렌더 시 unpack 오류 발생
```python
name_item, qitem, _ = self.render_queue[0]
```
- 위 구문을 snip render, hq render 두 부분에서 쓰고 있는데 snip render 의 경우에는 render_queue 리스트에 넣는 튜플 요소가 항상 두 개라 에러가 발생
```python
name_item, qitem, *_ = self.render_queue[0]
```
- unpack operator * 을 사용하여 두 경우 다 대응 가능하도록 수정

스닙랜더가 작동하지 않는 오류

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/bl_ui/space_topbar.py

[링크](https://www.notion.so/acon3d/Save-Copy-Filter-Toggle-region-9f196818884b4245a6b36200399ebb8d)
- Save Copy가 에이블러 오퍼레이터가 아닌 블렌더 내장 오퍼레이터 `bpy.ops.wm.save_as_mainfile(copy=True)`기 때문에 발생
- 내장 오퍼레이터를 쓰기 때문에 Open Recent에도 등록이 안되고 있음

Save Copy 초기 Filter, Toggle region 에러

---

release/scripts/startup/abler/export_tab/render_control.py

[이슈 카드](https://www.notion.so/acon3d/Issue-0085-Full-Render-16c5243ee4b24f5780cfbc8d885b5bf2)
[태스크 카드](https://www.notion.so/acon3d/Full-Render-a0087ba1ea5e494c9de1755dab20a4c4)
- 풀렌더 시 배경이미지가 보이지 않는 오류가 있음
- Acon3dRenderDirOperator 의 prepare_render 에서 render_type full 인 경우setup_background_images_compositor 실행시키도록 함

Full Render 시에 배경이미지 없이 렌더됨

---

release/scripts/startup/abler/lib/materials/materials_handler.py

[Object Properties에서 Shadow 토글 설정이 파일에 저장되지 않음](https://www.notion.so/acon3d/Object-Properties-Shadow-3426c2b724e449abafaa6a5b2d8713cf)
- **오브젝트 선택 → Style → Object Properties → Shadow 토글 해제 → 저장 → 저장된 파일 열기**하면 Shadow 토글이 계속 켜져있음
- 파일에 Shadow 토글 상태가 저장되지 않고 있음
- Slack Help
[https://acontainer.slack.com/archives/C02K1NPTV42/p1668424529542679](https://acontainer.slack.com/archives/C02K1NPTV42/p1668424529542679)
- 파일 오픈할 때, 재질을 다음 과정으로 설정함
- 각 오브젝트에 `toggle_each_shadow()` 가 실행되면서 각 재질의 `mat.ACON_prop.toggle_shadow` 로 그림자 정보를 불러옴
- 그런데 `pref.py` 에서 `apply_ACON_toon_style()` 을 실행하는데, 여기에서 `set_material_parameters_by_type()` 함수가 실행됨.
- 위에서 언급한 함수 내부에서 **Diffuse** 재질의 그림자를 항상 `True` 로 설정하고 있어 해당 부분 삭제

Object Properties에서 Shadow 토글 설정이 파일에 저장되지 않는 문제

---

release/scripts/startup/abler/scene_tab/scene_control.py

[링크](https://github.com/ACON3D/blender/compare/feature/skip-same-scene-name?expand=1)
- 이전 PR(https://github.com/ACON3D/blender/pull/225) 에서 post_fix `.001`을 붙여도 씬에 동일한 이름이 있을 때의 처리가 없었음
- post_fix를 while 안에서 확인하도록 변경

씬 추가 생성 후 삭제 시 에러 변경사항

---

release/scripts/startup/abler/lib/scenes.py

[Snap 기능을 비활성화 하기](https://www.notion.so/acon3d/Snap-8d631eebd5a8401b9b182a17420a72bd)
- `Snap to ...` 기능이 활성화가 되어 있는데, 사양서 기준으로 비활성화가 되어야함
- 해당 기능을 비활성화함.

Snap 기능 비활성화

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py

[링크](https://www.notion.so/acon3d/d6f8de22ac6c4aba8f5e88fa83aef26e)
- 렌더 파일 뷰어에서 더블클릭 시 렌더가 됨
- 파일 뷰어에서 빈 곳을 더블클릭할 때 동작이 발생하지 않아야함
- 블렌더에선 파일 뷰어에서 빈 곳을 클릭했을 때 실행이 되지 않음 → 블렌더와 에이블러에 차이가 있다고 판단
- 확인 결과 keymap에서 블렌더는 File Browser 내 Execute File Window가 `file.mouse_execute`이고 에이블러는 `file.execute`였음.
- 에이블러 키맵에서 file.execute → file.mouse_execute 로 변경해주니 파일 뷰어에서 빈 곳을 더블클릭해도 아무 동작을 하지 않음!

파일 뷰어에서 빈 곳에 더블클릭시 에러

---

release/scripts/startup/abler/lib/login.py

[링크](URL)
- 로그인 시에 계속 fail이 나서, 이유를 봤더니 psutil을 사용한 process 이름 받아오는 부분에서 해당 머신의 process들 중에서 상관 없는 에러가 나도 터지는 현상이 있어서 이를 고침
- process count 받아오는 부분을 try-except처리하고 exception이 있을 경우 그냥 True를 반환하도록 처리함.

상관없는 프로세스들의 오류에서도 로그인이 안되는 현상이 있어서 이를 고침

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py

[링크](https://www.notion.so/acon3d/Filter-option-Enable-ef19b89991e34601b950f902ca211257)
- Quick Render Viewport 클릭 시 브라우저 Filter option 초기값이 enable 됨

파일 뷰어 Filter option Enable 되는 에러

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/lib/import_file.py

[링크](https://www.notion.so/acon3d/7e2297af3d9d42f8b95fb880a2ecf743)
- 파일 브라우저의 옵션이 변경이 안됨
- `FileSelectParams`를 관리하는 함수는 `draw()` 라 draw내에서 파일 뷰어 옵션을 지정해줘야함
- `draw()`는 매번 그리기 때문에, 파일 뷰어 옵션을 지정해주면 **변경이 불가능함**(변경해도 draw에서 다시 옵션의 원래 설정값으로 그리기 때문)
- init에서 self.set_option 변수를 만들어 self.set_option이 None일 때만 draw에서 그리고 난 뒤 self.set_option = True로 설정 → 맨 처음 파일 브라우저를 열 때만 설정값이 적용
- 동일한 처리를 AconExportHelper에도 적용
- AconImportHelper, AconExportHelper를 상속받는 클래스 내 init에서 self.set_option이 상속받게끔 `super().__init__()` , `AconExportHelper.__init__()`의 처리를 해줌

파일 브라우저의 옵션이 변경 안되는 문제

---

release/scripts/startup/abler/operators.py

[이슈 #0076](https://www.notion.so/acon3d/Issue-0079-d42c7df26a1040379790c41289d83c2c)
- 에이블러를 클라이언트를 두 개 실행 후, 둘다 로그인
- 한 클라이언트 (A) 에서 정상적으로 로그아웃
- 다른 클라이언트 (B) 에서 로그아웃하면 아무 반응이 없음
- 혹은 파이썬 에러 메세지가 출력됨
- 클라이언트 A에서 로그아웃을 하더라도 켜져있는 클라이언트 B는 에이블러를 사용하는데 이슈가 없음
- 클라이언트 B에서 로그아웃을 시도했을 시에, 로그아웃이 가능하며, 에러메세지가 출력되지 않음
- path_cookiesFile이 존재하지 않아도 로그아웃 오퍼레이터 실행 시에 제대로 기작이 작동되도록 수정

여러 에이블러 클라이언트 실행 중에 로그아웃을 해도 아무 반응이 없음

---

release/scripts/startup/abler/export_tab/export_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/string_helper.py
source/blender/editors/interface/interface_templates.c

REMOVE year/month/day from timestamp_to_string function REMOVE tooltip from progress
[태스크 카드](https://www.notion.so/acon3d/328b595e2570421d8aabadead6e5496d)
[슬랙 쓰레드](https://acontainer.slack.com/archives/C01K142MCNS/p1668734383299789)
- 프로그레스 템플릿에서 글자가 잘리는 이슈가 있어서 UI 조정
- 아이콘과 텍스트를 분리하고, 날짜를 없애기 시각/시간만 남겨서 유저가 보는데에 불편함이 없도록 변경
- 기존에 삭제되었던 프로그레스바의 tooltip 코드가 작업하면서 다시 생겨난 것 같아 다시 삭제

프로그레스 템플릿 UI 조정

---

build_files/buildbot/codesign/base_code_signer.py

[CVE-2007-4559](https://github.com/advisories/GHSA-gw9q-c7gh-j9vm)
[참고](https://isarc.tachyonlab.com/5338)
Hi, we are security researchers from the Advanced Research Center at [Trellix](https://www.trellix.com/). We have began a campaign to patch a widespread bug named [CVE-2007-4559](https://github.com/advisories/GHSA-gw9q-c7gh-j9vm).
[CVE-2007-4559](https://github.com/advisories/GHSA-gw9q-c7gh-j9vm) is a 15 year old bug in the Python tarfile package. By using extract() or extractall() on a tarfile object without sanitizing input, a maliciously crafted .tar file could perform a directory path traversal attack. We found at least one unsantized extractall() in your codebase and are providing a patch for you via pull request.
The patch essentially checks to see if all tarfile members will …

.tar 파일 취약점 보완 (@TrellixVulnTeam)

---

release/scripts/startup/abler/lib/addons.py
release/scripts/startup/abler/pref.py

[SKP Import 애드온을 에이블러 시작할 때 실행](https://www.notion.so/acon3d/SKP-Import-8dc51f62ae6740e8a09756b37bb9d9bb)
- 에이블러 실행할 때 SKP Importer 애드온이 켜지지 않고 있어 사용할 수 없는 에러 및 UI 에러가 발생함.
- 에이블러를 실행할 때 활성/비활성 애드온을 관리함
- 기존 `disable_preference_addons()` 함수에서는 사용하지 않을 애드온을 끄기만 했으므로, 켜주는 애드온도 같은 함수에서 다루기 위해 함수명을 `preferences_addons()` 로 수정함
- 애드온을 켜주는 과정도 추가
- 켜야할 애드온 `io_skp` 를 추가

에이블러 실행할 때의 애드온 관리

---

release/scripts/startup/abler/scene_tab/scene_control.py

[링크](https://www.notion.so/acon3d/0c7d5198c5dd4dbe8d17109c444f4a51)
- 씬 생성시 파일 넘버링 과정에서 에러가 재발생해 태스크 재오픈합니다.
- 튜플로 변경했다가 에러 발생해 다시 리스트 인덱싱으로 변경했습니다. (네임에 "."이 없는 경우 rsplit 결과가 튜플이 아님)

씬 추가 생성 후 지우려고 할 시 뜨는 에러 재처리

---

release/scripts/startup/abler/export_tab/render_control.py

[이슈 링크](https://www.notion.so/acon3d/Issue-0095-Quick-Render-Viewport-ABLER-File-View-c5cad0a509b6444eb0faddb5c2082527)
- TC번호: abler_export_saveQuick_UI_01
- Quick Render Viewport 클릭 시 팝업 이름이
- ABLER file view인 상태
- Save Image Files 이어야 함
- quick render에 file view layer 제목이 이상하게 뜨는 문제 해결. 
- 워닝이 뜨는 이슈 있긴 함.

Quick Render Viewport 클릭 시 브라우저 이름이 ABLER File View인 문제

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/camera_tab/camera_control.py
release/scripts/startup/abler/export_tab/export_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/scene_tab/layer_control.py
release/scripts/startup/abler/scene_tab/object_control.py
release/scripts/startup/abler/scene_tab/scene_control.py
release/scripts/startup/abler/style_tab/styles_control.py

[링크](https://www.notion.so/acon3d/Scene-Style-7c0642e74c264d1a9624fb30093360db)
- Scene 탭과 Style탭의 순서가 바껴서 나옴
- init에서 register 순서는 적정상태 대로 General > Camera > Scene > Style > Export
- `bl_options = {"HIDE_HEADER"}` 이 적용된 패널 순서대로 배치됨(블렌더 내장 순서로 보임)

Scene 탭과 Style탭의 순서가 바뀐 에러

---

release/scripts/startup/abler/scene_tab/layer_control.py
release/scripts/startup/abler/scene_tab/object_control.py
release/scripts/startup/abler/scene_tab/scene_control.py

[링크](https://www.notion.so/acon3d/Scene-Scenes-24ebc55302ee45df9779edcf7b0052ab)
- Scenes -> Scene 탭 이름 변경
- bl_category = "Scenes" -> "Scene"

Scene 탭 이름이 Scenes로 되어 있는 문제

---

release/scripts/startup/abler/camera_tab/background_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py

[태스크 카드](https://www.notion.so/acon3d/File-View-Layer-6a807d0a00194e58bf101b1b32cebd0f)
- Menu> Open
- Menu> Import> FBX
- Menu> Import> SKP
- Menu> Import> Blender
- General> Open
- General> Import
- Camera> Background Images> Default Image
- Camera> Background Images> Custom Image
위 부분에서 필터가 켜져있어야 함.
- AconImportHelper 에 use_filter 변수를 추가하여 조건을 두었습니다.

파일을 열 때 File View Layer에서 필터 옵션이 꺼져있는 문제

---

release/scripts/startup/abler/general_tab/general.py

[태스크 카드](https://www.notion.so/acon3d/Import-SKP-efcd478b18df4a469b7573e35824f230)
- 패널의 닫지 않고 Import SKP 를 연속으로 하는 경우 Import SKP 패널의 진척도가 100% 에서 변경되지 않음
- acon3d.close_skp_progress 함수를 import 시작 전에도 실행하도록 했습니다.

Import SKP 를 연속으로 했을 때 패널이 갱신되지 않는 문제

---

source/blender/editors/space_file/file_ops.c

[파일 브라우저에서 북마크에 없는 디렉터리 선택 후, 북마크 Top 기능을 사용하면 최상위 북마크가 삭제되는 문제](https://www.notion.so/acon3d/Top-baa9d05d98fc4950a49c7e104186c4a0)
- 파일 브라우저에서 2개 이상의 북마크를 추가하고, 추가되지 않은 디렉터리를 선택하고 Move Bookmark (위로) / Move to Top 기능을 사용하면 가장 최상위 북마크가 삭제되고 있음
- index를 하나하나 예외 처리하지 말고, 북마크에 없는 디렉터리를 선택했을 때는 북마크의 기능이 작동하지 않으면 될 것 같다고 생각함.
- 북마크에 없는 디렉터리의 `act_index` 의 값은 `-1` 이고, 이 값에 대해서 북마크 정렬 기능 동작 없이 오퍼레이터를 종료하면됨.

북마크에 없는 디렉터리의 북마크 기능 사용을 제한

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/startup_flow.py
release/scripts/startup/abler/warning_modal.py

[태스크 링크](https://www.notion.so/acon3d/Import-skp-import-cf16e4715ac7409594c236d2f3f02cef)
[SKP Converter PR](https://github.com/ACON3D/SKP_Converter/pull/95)
[translations PR](https://github.com/ACON3D/blender-translations/pull/40)
- Import SKP 하기 전 팝업이 보여야 합니다.
- ImportSKPModalOperator 추가하여 팝업 띄울 수 있도록 함.
- ImportAcceptOperator 추가하여 팝업에서 Import 할 수 있도록 함.
- CloseBlockingModalOperator 에 description_text 추가하여 상황에 따라 메시지 다르게 보여줄 수 있도록 수정함.

Import skp 실행 시 import 실행 여부를 묻는 팝업이 노출되지 않음

---

release/scripts/startup/abler/scene_tab/scene_control.py

[링크](https://www.notion.so/acon3d/0f06378a1fe0486e9a260ffae9b398a5)
- 씬을 삭제 시 바로 다음 순서의 씬(생성순 내림차순)으로 전환되어야 함 (맨 아래 씬 삭제 시 가장 위의 씬으로 이동함)
- 씬 삭제 시 다음 뷰포트에 출력된 씬이 씬 리스트에서 포커스되어야 함

씬 삭제 후 포커스된 씬이 없어져서 씬 삭제 시 오류가 발생하는 문제

---

release/scripts/startup/abler/startup_flow.py

[태스크 카드](https://www.notion.so/acon3d/login-auto-324c054e76b9487cab56e8dc4d3f1436)
- 파일 오픈할 때마다 믹스패널의 login auto 도 같이 실행됨
- `bpy.data.filepath`가 있을때만 login auto가 실행되도록 함.

login auto가 파일 열때마다 실행되는 문제

---

release/scripts/startup/abler/export_tab/render_control.py

[태스크 카드](https://www.notion.so/acon3d/a1974bb80b4e4c4d82764994f2678f6b)
- 전체 렌더는 각 렌더 완료 시 트래킹
- 퀵, 스닙 렌더는 렌더 시작 시 트래킹되고 있음
- 퀵, 스닙 렌더 렌더 완료 후 트래킹하도록 변경

퀵 렌더, 스닙 렌더의 트래킹 시점이 완료 시점이 아님

---

release/scripts/startup/abler/export_tab/render_control.py

[링크](https://www.notion.so/acon3d/15930245b0004ed2ae72aa142dc8149e)
- 전체 렌더 시 블룸이 적용이 안됨
- render_type으로 use_bloom 조건 맞춰주기

고품질 전체 렌더 시 블룸이 적용 안되는 문제

---

release/scripts/startup/abler/startup_flow.py

[태스크](https://www.notion.so/acon3d/69d7e4f44a1742a4a4918b3a534c00dd)
[이슈](https://www.notion.so/acon3d/Issue-0116-79ed8183a58a4d999852f2235b11af30)
[blender-translations PR](https://github.com/ACON3D/blender-translations/pull/46)
- 로그인 연속 실패 팝업의 영문 문구가 잘려서 보인다.
- 로그인 연속 실패 팝업의 영문 문구를 짧게 변경하였습니다.

로그인 연속 실패 팝업의 영문 문구가 잘림

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py

[태스크](https://www.notion.so/acon3d/Save-Quick-Render-Save-As-ccbc00eb651c44acba202ffcd8df8a3f)
[이슈](https://www.notion.so/acon3d/Issue-0119-Save-Quick-Render-Save-As-18cb4369bcc541c5864a492810e8500f)
Save / Save as / Save Copy / Render Quick 시
- 파일명 구좌에 빈 값이 들어가면, 현 디렉토리의 주소를 가져오고, 그 디렉토리의 주소 뒤에 .blend, .png 등을 붙여서 저장
- 위 과정에서 상위 폴더로 올라가면 쓰기 권한이 없어서 파일 저장을 실패하고 오류가 발생
- check_path 함수를 추가하여 파일명을 빈 채로 저장하면 해당 디렉토리에 디폴트 값으로 저장되도록 함.
- 디렉토리인지 체크 후 해당 주소에 디폴트 값 추가

Save, Quick Render 브라우저의 파일명 구좌가 비어 있는 상태에서 Save As를 실행했을 때 오류

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py

[태스크](https://www.notion.so/acon3d/42ba1e76de4e4f39ba55bfa1a8b4ed37)
[이슈](https://www.notion.so/acon3d/Issue-0131-b1e83ec1aca3497098ef61ee722db095)
- 저장 이력이 없는 파일 렌더 시, 파일 브라우저 우측에 문구가 보여야 합니다.
- SaveOperator 에 is_render 을 추가하여 렌더 프로세스 도중에 저장을 실행했을 때만 문구가 보이도록 하였습니다.

저장 이력이 없는 파일 렌더 시 뜨는 파일 브라우저 우측 문구 누락

---

source/blender/makesrna/intern/rna_wm_api.c

[Slack 에러 스레드](https://acontainer.slack.com/archives/C02K1NPTV42/p1669959302530369)
- 변수 parm의 uninitialized 문제로 MacOS (Intel) (항상) 및 Windows (가끔) 빌드 문제가 발생하고 있었음
- RNA_def_enum() property를 parm에 대입하여 초기화

File view title의 property parameter 초기화로 빌드 문제 수정

---

release/scripts/startup/abler/general_tab/general.py

[링크](https://www.notion.so/acon3d/Import-426154b27f764469aae499ca881e0096)
- 에이블러가 import 이후 파일의 변경 사항을 인식하지 못하고 있는 문제 발생
- 그래서 프로그램을 종료하거나 렌더를 할 때 **저장**을 확인하는 과정이 생략됨
- import 후 is_dirty = True로 설정이 안됨 -> is_dirty = True가 되려면 undo가 있어야함

Import 기능 후 종료 시 저장 여부를 묻지 않는 문제

---

release/scripts/startup/abler/export_tab/render_control.py

[태스크](https://www.notion.so/acon3d/ccaebd5b20ab433686d4c8ca7eb57192)
[이슈](https://www.notion.so/acon3d/Issue-0123-a9ed7aa483074ffe981e163663ec9184)
- 그림자 렌더 시 투명체가 불투명 처리되어서 빛이 들어오지 않는 문제가 있음
- 그림자 렌더 시 발광체가 빛나지 않는 문제가 있음
- 텍스쳐 렌더 시 투명체가 불투명 처리되어서 투명 물체 뒤쪽이 보이지 않는 문제가 있음
- 아래에서 말하는 기존 값은 `material_handler.set_material_parameters_by_type` 로 설정하는 값입니다.
1. texture, shadow - Refelction 만 Opaque 처리, 나머지는 기존값 그대로
2. line - 모두 Opaque 처리
3. full - 기존 값 그대로

고품질 렌더가 제대로 작동하지 않는 문제

---

.gitmodules

[링크](https://www.notion.so/acon3d/014dd21d615f4f928e9a806b541430eb)
- SKP_Converter 내 skp_importer 브랜치가 main으로 머지돼 빌드 시에 main을 바라보도록 변경
- 빌드 시에 브랜치 확인하는 .gitmodule의 io_skp 브랜치를 main으로 변경했습니다.

에이블러 빌드 io_skp 브랜치 변경

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/bl_operators/wm.py

[Search in ACON3D UI를 General 탭에 추가](https://www.notion.so/acon3d/Search-in-ACON3D-UI-General-9b8cb8e6bfef4e09ab624b3cb553d287)
[Open ACON3D UI를 General 탭에 추가](https://www.notion.so/acon3d/Open-ACON3D-UI-General-6f5a59dd039b4d9f8f851dd643a60d11)
- 에이블러가 에이콘에 어떤 간접 가치를 주는지 정량적으로 확인하기 위해 General탭에 두가지 기능을 추가하기로 함
- General 탭 상단에 `ACON3D Asset Store`라는 버튼(기능)을 추가하여 abler 사용자가 acon3d 홈페이지로 이동할 수 있도록 해야함
- General 탭 상단에 String input을 받아서 `Search`버튼을 누르면 현재 abler의 언어 세팅에 따라 acon3d 검색창으로 연결되도록 해야함

에이블러에서 에이콘으로 연결되는 Open과 Search 기능 추가

---

release/scripts/startup/abler/pref.py

[그리드 오류 발생의 방어 코드 작성-테스크 카드](https://www.notion.so/acon3d/20ffe5f8c101489c85d4f48da6f68cf0)
[센트리 에러](https://sentry.io/organizations/carpenstreet/issues/3748549901/?referrer=slack)
- VIEW 3D가 아닌 다른 화면에서 그리드를 제어하려는 것으로 보임
- 해당 부분 방어 코드로 처리하기
- `find_screen_acon3d()`에서 `bpy.data.screens["ACON3D"].areas[0].spaces[0].type`이 `"VIEW_3D"`인지 확인함

view_3d가 아닌 다른 화면에서 화면 그리드가 작동하는 문제

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/general_tab/general.py

[공백 포함 폴더명으로 저장하는 오류 발생 후, 고품질 렌더를 연속으로 했을 때 발생하는 에러 - 테스크 카드](https://www.notion.so/acon3d/e7a8a6575b8e4545a825d117407cc43e)
- 
- `basename.rstrip()`으로 파일명 뒤에 오는 공백이 없도록 함.(저장할 때, 랜더한 후)

파일명 뒤에 공백이 들어가는 발생하는 문제

---

release/scripts/startup/abler/lib/materials/materials_handler.py

[change_toon_shading_brightness 에서 nodes.get 의 결과가 비어있을 때 오류 발생 - 에러 카드](https://www.notion.so/acon3d/change_toon_shading_brightness-nodes-get-c95ce3fc68ee4e4b8b64e56a8bdf8609)
[material 의 node_tree 내에 nodes 가 없는 경우에 에러 발생 - 에러 카드](https://www.notion.so/acon3d/material-node_tree-nodes-8dfb5b3c6356461b9127c18c3b936743)
- 유저가 노드를 삭제해서 노드가 존재하게 되지 않았을 때 생기는 문제로 추정됨
- 유저가 노드를 새로 생성해서 노드트리가 존재하게 되지 않았을 때 생기는 문제로 추정됨
- node가 존재하지 않을 경우를 If문으로 확인하는 방지코드를 작성함
- nodetree가 존재하지 않을 경우를 If문으로 확인하는 방지코드를 작성함

node가 존재하지 않을 경우에 대한 방지 코드

---

release/scripts/startup/abler/warning_modal.py

[abler.warning_modal에서 self.layout이 없을 때 에러 발생  - 에러 카드](https://www.notion.so/acon3d/abler-warning_modal-self-layout-d360a1e086f1473880df8b98ba176cc5)
- WM_MT_splash_modal의 draw() 함수에서 `self.draw_func(self.layout)`을 실행할 때 self.layout이 None이라 에러 발생
- self-layout이 None인지 확인하는 if문 추가

abler.warning_modal에서 self.layout이 없을 때 에러 발생

---

release/scripts/startup/abler/lib/scenes.py

[ViewLayer별로 오브젝트가 다르게 사용되는 blend 파일에 대하여 refresh_look_at_me 오류 - 노션 에러 카드](https://www.notion.so/acon3d/ViewLayer-blend-refresh_look_at_me-84d7329f0c214591b4692ca6f98764b8?pvs=4)
- `refresh_look_at_me`에 있는 obj.select_set(True) 실행시, obj가 활성 ViewLayer에 있지 않아서 선택되지 못함.
- `for문`에서 view_layer에 있는 object들로 범위를 좁힘.

view_layer에 오브젝트가 없어서 refresh_look_at_me 함수에서 발생하는 문제

---

release/scripts/startup/abler/export_tab/render_control.py

[노드 편집할 때 에러 발생 시 에이블러 팝업으로 알려주기 - 노션 에러 카드](https://www.notion.so/acon3d/95006e2b35dd49f3aef1c3d5b4ef4b3c?pvs=4)
- `ACON_nodeGroup_combinedToon`노드를 수정하다가 Attribute 에러가 발생함.
- 재현은 불가능 했음.
- Attribute에러가 발생한 부분에 `acon3d.alert`로 노드를 수정하면 에러가 발생할 수 있다는 내용의 팝업을 띄움.

AttributeError alert 추가

---

release/scripts/startup/abler/export_tab/render_control.py

[OS에러 발생 시에 유저에게 알리기 - 노션 에러 카드](https://www.notion.so/acon3d/OS-93e7bafa729c414fb37924af4dec749b?pvs=4)
- `render_control.py`에서 os에러가 발생함.
- 재현은 불가했음.
- OSError가 발생하면 `acon3d.alert`로 올바른 디렉토리 명을 입력하라는 내용의 팝업을 띄움.

OSError alert 추가

---

release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/abler/lib/import_file.py

[저장을 할 때 폴더에 접근하고, OS에서 삭제한 후에 저장을 실행하면 발생하는 문제 - 에러 카드](https://www.notion.so/acon3d/OS-ad6bad4ef5a44d839aa78bd9606534dd)
- 유저가 파일경로가 사라진 상태에서 파일을 저장하려고 할 때 에러가 발생함
- 가장 최근에 저장한 디렉토리안에 untitled라는 새로운 파일을 생성 후, 그곳에 파일 저장

OS에서 직접 삭제한 파일 경로에 파일을 저장하려고 할때 발생하는 문제

---

release/scripts/startup/abler/pref.py

[grid_on_when_selected 에서 selected_objects 가 없을 때 에러 발생 - 에러 카드](https://www.notion.so/acon3d/grid_on_when_selected-selected_objects-425a307e30874400bf02ff14b3966a66?pvs=4)
- `selected_objects`가 없어서 에러가 발생함.
- 재현하지 못함.
- `selected_objects`를 확인하는 `if문` 추가

SWTASK-31 grid_on_when_selected에서 selected_objects가 없어서 발생하는 문제

---

release/scripts/startup/abler/export_tab/render_control.py

[폴더나 파일이 없을 때 FileNotFoundException이 발생 - Jira 카드](https://carpenstreet.atlassian.net/browse/SWTASK-64)
- 렌더 후 저장하는 과정에서 파일경로를 찾지 못해서 에러가 발생함.
- 원인은 [OS에서 직접 파일경로를 삭제한 후 발생하는 에러](https://github.com/carpenstreet/blender/pull/295)로 추정함.
- 파일경로에 대한 처리는 했으므로 `acon3d.alert`로 에러에 대한 방지 코드를 작성함.

SWTASK-64 폴더나 파일이 없을 때 FileNotFoundError이 발생하는 문제

---

release/scripts/startup/abler/pref.py

[grid_on_when_selected 에서 selected_objects 가 없을 때 에러 발생 -Jira 카드](https://carpenstreet.atlassian.net/browse/SWTASK-67)
- 기존에 바꾼 코드에서 `show_grid`라는 boolean값이 if문 안에서 정의되어 에러가 발생함
- `show_grid`정의 하는 부분을 if문 밖으로 수정함

SWTASK-67 grid_on_when_selected 에서 selected_objects 가 없을 때 에러 발생

---

release/scripts/startup/abler/lib/scenes.py

[활성화 된 씬이 없는데 접근하는 문제-노션 카드](https://www.notion.so/acon3d/86ba61de6ef14e0fb236fe0425584db1?pvs=4)
[활성화 된 씬이 없는데 접근하는 문제-Jira 테스크](https://carpenstreet.atlassian.net/browse/SWTASK-32?focusedCommentId=14073&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14073)
- 활성화 된 씬이 없어서 에러 발생
- 활성화 된 씬이 없다는 건 `active_scene_index`가 없다는 것이 되므로 확인하는 `if문` 추가

SWTASK-32 load_scene_by_index 함수에서 active_scene이 없어서 발생하는 문제

---

release/scripts/startup/abler/lib/file_view.py
release/scripts/startup/abler/lib/render.py

[file_view_title에서 set_fileselect_title이 없는 에러-테스크 카드](https://www.notion.so/acon3d/file_view_title-set_fileselect_title-98b55d3116f942f69759f0d63dd7be35)
- file_view.py에서 window_manager에 set_fileselect_title이 없어서 에러 발생
- `file_view_title()`에서 `bpy.context.window_manager.set_fileselect_title`를 확인해줘야 함.
- `bpy.context.window_manager.set_fileselect_title`를 확인하는 if문 추가

SWTASK-38 오브젝트안에 프로퍼티가 존재하지 않을 경우를 방지하지 않아 생긴 문제

---

release/scripts/startup/abler/export_tab/export_control.py
release/scripts/startup/abler/lib/render.py

[카메라가 없을 때 Quick Render 에러 발생-태스크 카드](https://www.notion.so/acon3d/Quick-Render-2db84d5e85634219ac3c179003b7dc28)
- 카메라가 없을 때 Quick Render 에서 에러가 발생함
- 세가지 랜더에 모두 카메라 여부 확인하는 if문 추가
- 세가지 랜더에 모두 카메라 여부 확인하는 if문 추가

SWTASK-39 랜더 할 때 카메라가 없어서 발생하는 문제

---

release/scripts/startup/abler/lib/objects.py

[Look At Me 기능을 사용할 때, Python의 최대 재귀 깊이를 초과해서 에러 발생 - Jira 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-49)
- 한번에 많은 개체들에게 `Look at me`를 적용하면 Python recursion limit을 초과해서 Recursion Error가 발생함.
- `sys.setrecursionlimit()`을 이용해 recursion limit을 C의 max int 값인 `2147483647`으로 설정함.
- 하지만, 아직도 Look at me를 실행하면 터지는 에러가 발생해 새로운 Error 티켓을 만들것임.

SWTASK-49 Look At Me 기능을 사용할 때 Recursion Error발생

---

release/scripts/startup/abler/scene_tab/object_control.py

[Group Navigation 에서 선택된 개체가 없을 때 go_top 에러 발생 - 에러카드](https://www.notion.so/acon3d/Group-Navigation-go_top-f5f6b128c437483cabf2e228b00e8f6a)
[active_object가 없을 때 그룹네비게이션 parent 에러- 에러카드](https://www.notion.so/acon3d/active_object-parent-8382b758e6a84490a6f46d1973253f7a)
- 오브젝트가 없거나 선택되지 않았을 때 그룹 네비게이션을 사용하면서 발생하는 문제
- obj가 none인지 확인하는 if문과 go_up과 go_top의 if문 조건을 동일하게 맞췄습니다.

오브젝트가 없거나 선택되지 않았을 때 그룹 네비게이션을 사용하면서 발생하는 문제

---

release/scripts/startup/abler/startup_flow.py

[관련 지라 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-103?focusedCommentId=16625&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16625)
- 아이디의 오류(존재하지 않는 아이디)로 인한 로그인 문제를 유저에게 알리고 있지 않음. 
- 로그인 오류 시, 띄워주는 문구인 wrong messages에 “회원정보를 찾을 수 없습니다.” 문구를 추가함.

SWTASK-103 존재하지 않는 아이디로 인한 로그인 오류 관련 문구 추가

---

release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/scene_tab/scene_control.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-91)
- 에이블러에서 다양한 프리셋이 있지만, 기본 설정값으로 지정된 프리셋이 없음. 오류경험의 일종이므로 생성해야함.
- preset에 default 항목 추가
- default 선택 시 prop 값 설정
- default는 ko.po에 이미 '기본 값'으로 번역되고 있음

SWTASK-91 기본 설정값 프리셋 추가

---

abler_requirements.txt

[직접 수익화 2번째 피쳐를 위한 pywin32 module](https://carpenstreet.atlassian.net/browse/SWTASK-77)
[export psd를 위한 photoshop-python-api, pillow module](https://github.com/carpenstreet/blender/pull/117)
- 관련 모듈들을 abler_requirements.txt에 추가되면 추가 설치하는 과정이 생략되어도 되기 때문에 추가하기로 함.
- [관련 Jira 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-134)

SWTASK-134  abler_requirements.txt에 필요한 모듈 3가지 추가

---

release/scripts/startup/abler/lib/scenes.py

[Jira 티켓 - 씬 개수를 벗어나는 범위의 씬 index에 접근하는 문제](https://carpenstreet.atlassian.net/browse/SWTASK-118)
- 씬 이름을 변경하면서 기존에 저장된 active_scene_index 와 scene_col 의 index 범위가 연동되지 않아서 범위를 벗어난 index에 접근할 때 발생하는 것으로 보임
- active_scene_index 를 현재 scene_col 번호에 맞게 업데이트 하면 될 것 같음
- add_scene_items_to_collection()이라는 기존에 있던 함수(scene_col과 outliner의 scene들을 맞춰 update해주는 함수)를 추가해줌.

SWTASK-118  scene_col의 scene과 outliner의 scene이 맞지 않아서 발생하는 문제

---

release/scripts/startup/abler/lib/materials/materials_handler.py

- 관련 에러: [Sentry](https://carpenstreet-np.sentry.io/issues/3986664346/?project=4504597190803456&referrer=slack)
- 예상 원인 및 재현
- 재현 불가
- 카메라 오브젝트 없이 Mesh 로 배경 이미지 속성에 접근하는 방법을 모르겠음
- 해결 방안
- `context.scene.camera.data`가 카메라 오브젝트인지 아닌지 확인하는 과정이 필요할 것 같음
- 카메라 오브젝트를 선택했을 때만 배경 이미지 속성에 접근할 수 있도록 허용

[SWTASK-116] 카메라 선택 없이 배경 이미지 속성에 접근하는 버그

---

release/scripts/startup/abler/style_tab/styles_control.py

[에러 링크](https://carpenstreet-np.sentry.io/issues/3974831978/?project=4504597190803456&referrer=slack)
[Jira 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-105?atlOrigin=eyJpIjoiYTg5MDIxNTBlZmFjNDJkOWJhN2ViOWUyZTBmNGY2Y2UiLCJwIjoiaiJ9)
- `slot.material.node_tree`가 None인 상황에서 에러가 발생했음
- 아래와 같은 코드를 추가하고 해당 내용이 왜 추가되었는지 주석도 추가함.
```python
if not ma.node_tree:
return
```

SWTASK-105 slot.material.node_tree가 None인 에러 발생

---

release/scripts/startup/abler/lib/scenes.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-207)
- default 씬 설정 시 bloom이 기본값으로 돌아가지 않음
- 기본 씬에서 bloom 프로퍼티를 변경한 후 "Outdoor Sunset" 같은 항목으로 씬을 변경해도 화면의 프로퍼티는 바뀌는데 UI 프로퍼티는 바뀌고 있지 않음
- `create_scene()`에서 prop의 bloom 프로퍼티를 바꿔줘도 create_scene() 시의 prop은 이전 씬을 바라보고 있음
→ bloom 업데이트 함수를 load_scene에서 직접 실행해줘야함
```
def load_scene()
(...)
bloom.change_bloom_threshold(None, context)
bloom.change_bloom_knee(None, context)
bloom.change_bloom_radius(None, context)
bloom.change_bloom_color(None, context)
bloom.change_bloom_intensity(None, context)
bloom.change_bloom_clamp(None, context)
```
- (이전 버전에도 있는 버그) 기본 씬에서 bloom 프로퍼티를 변경한 후 "Outdoor Sunset" 같은 항목으로 씬을 변경해도 화면의 프로퍼티는 바뀌는데 UI 프로퍼티는 바뀌고 있지 않음
- new_scene.eevee.bloom_knee = 0.5 이런식으로 eevee의 프로퍼티를 직접 바꾸면 UI의 프로퍼티는 변경되지 않음
→ UI 프로퍼티(prop)도 …

default 씬 설정시 bloom이 기본값으로 돌아가지 않는 에러

---

release/scripts/startup/abler/scene_tab/object_control.py

[add_group_list_from_collection 에서 obj 가 없는 경우 에러 발생- jira 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-197)
- obj.parent가 존재하지 않을 경우에 add_group_list_from_collection에서 에러가 발생함
- if obj.parent를 확인하기 전에 if obj를 확인해주어야 하기 때문에 if obj 안으로 넣어줌

SWTASK-197 add_group_list_from_collection에서 obj가 없는 경우 발생하는 에러

---

release/scripts/startup/abler/scene_tab/object_control.py

[그룹 네비게이션에서 type 오류로 인해 생기는 에러 - jira 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-201)
- while문 안에서 obj값이 업데이트 되지 않는 버그로 인한 오류임을 확인함.
- 가독성을 위해 기존에 작성되었던 코드([해당 PR](https://github.com/carpenstreet/blender/pull/293) 머지 이전)에서 obj가 없을 때만 return하는 방식이 낫다고 판단하여 go_top()과 go_up()을 수정함
- go_bottom()과 go_down() 함수에서는 obj의 존재 여부를 확인할 필요가 없다고 판단하여 또한 언급된 pr 머지 이전의 형태로 복구함
- 기존 go_up() 함수에서 obj.parent.parent의 존재 여부를 확인하고 있어, 최상위 오브젝트의 child는 go_up() 함수 적용대상이 아닌 버그를 발견하여 if obj.parent만 확인하도록 수정함

SWTASK-201 group selection에서 obj의 값이 업데이트 되지 않아 발생하고 있는 에러

---

.gitignore
source/blender/blenfont/intern/blf_font.c

[Jira 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-223?atlOrigin=eyJpIjoiODMwNTZkYzI2ODg3NDYxZGEyZDU4YmQ3YTBmNGYyNDUiLCJwIjoiaiJ9)
- macOS에서 에이블러 한글 자모 깨지는 현상이 있음 (파일 뷰어에서만 그럼)
- `blf_font_draw_ex` 함수에서 string들에 대한 while 문을 도는데, 이때 자모를 합칠 수 있는 케이스를 미리 선별해서 합친 문자의 unicode로 새로운 unsigned int array를 채워줌.
- 나름 큰 변경사항이다보니 모든 피드백을 다 받아들이겠습니다. 빡시게 코멘트 해주세요
- 윈도우 컴이 있으신 분들은 윈도우에서 한번 빌드하여 확인 해봐주시면 감사하겠습니다.
- 쌍자음에 대해서 macOS에서는 잘 적용된 것을 확인하였습니다. 혹시 모르니 더블체크 부탁드리겠습니다.

SWTASK-223 macOS 에이블러 파일 뷰에서 한글 자모 깨지는 현상 수정

---

release/scripts/startup/abler/scene_tab/object_control.py

[관련 지라 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-219)
- 처음 오브젝트를 선택했을 때 그 오브젝트가 children이 있는경우에도 go_down이나 go_bottom이 작동하지 않음
- 처음 오브젝트를 클릭했을 때에도 go_down과 go_bottom이 적용되게 함.
- 또한 refresh_stack()이라는 함수로 클릭한 obj와 관련이 없는 것들이 stack에 있다면 stack을 초기화 함

SWTASK-219 Group Navigation 에서 go_down, go_bottom 이 처음 오브젝트 선택 시 실행되지 않는 문제

---

intern/ghost/GHOST_ISystem.h
intern/ghost/intern/GHOST_ISystem.cpp
intern/ghost/intern/GHOST_SparkleUpdater.mm

[이슈](https://carpenstreet.atlassian.net/browse/SWTASK-259?atlOrigin=eyJpIjoiMGZlZWMxNTQ0NTJmNDUxNmFiNmZjMTNlMjg0YjYwMjciLCJwIjoiaiJ9)
- Sparkle Updater 등 새로 추가한 Object 들이 system 이 메모리에서 해제될 때 같이 해제되게 한다.ㅋ
- SparkleUpdater 의 소멸자를 추가했습니다.
- GHOST_ISystem 에 disposeUpdater 함수를 만들고 해당 함수를 disposeSystem 시 호출하도록 하였습니다.

SWTASK-259 Updater 메모리 해제하는 로직 추가

---

release/scripts/startup/abler/lib/scenes.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-263)
- 프리셋 씬에서 exposure, gamma 값에 대한 설정이 없음
- 씬 설정 시 exposure, gamma 값에 default 설정(default 씬 이외에 다른 씬에도 추가해줘야 exposure, gamma 값 변경해도 영향을 받지 않음)
- load_scene에서 프로퍼티 update 함수를 추가

기본값 프리셋 적용시 에러

---

intern/ghost/GHOST_C-api.h
intern/ghost/GHOST_ISystem.h
intern/ghost/intern/GHOST_C-api.cpp
intern/ghost/intern/GHOST_ISystem.cpp
intern/ghost/intern/GHOST_SparkleUpdater.h
intern/ghost/intern/GHOST_SparkleUpdater.mm
source/blender/windowmanager/intern/wm_window.c

[이슈](https://carpenstreet.atlassian.net/browse/SWTASK-251?atlOrigin=eyJpIjoiMzQ5NWUxMTFlOTQwNGMyMjg0ZDJlMjYxMjJlYmNjZTEiLCJwIjoiaiJ9)
- updater 라는 이름은 윈도우, 맥 두 경우 다 쓰이는 것처럼 느껴져서 명확한 이름으로 변경하는 것이 좋아 보임
- updater 에서 sparkleUpdater 로 변수/함수 명을 변경하였습니다.
- SparkleUpdater 클래스에서 사용하지 않는 함수를 삭제했습니다.

SWTASK-251 MacOS 전용 업데이터 변수/함수/클래스 이름 명확하게 수정

---

release/darwin/ABLER_macOS_Release.sh
release/darwin/bundle.sh
release/darwin/generate_appcast_and_image.sh

[이슈](https://carpenstreet.atlassian.net/jira/software/c/projects/SWTASK/boards/22?modal=detail&selectedIssue=SWTASK-279&assignee=63c78e769d59ec705fec7f44)
- 빌드 내용 개선
- 빌드 오류 해결
- `.o` 파일 코드사인 추가
- `generate_appcast` 의 동작이 실제와 달라 `generate_appcast_and_image` 로 이름변경
- 파일 이름 구분을 위해 `_cpu` 추가
- notorization 중간 대기시간 1/10로 줄이고, 루프 횟수를 10배로 변경

SWTASK-279 새로운 맥북에서 빌드 / 배포되지 않는 문제

---

release/scripts/startup/bl_ui/space_view3d.py

DELETE - Shift+A 커맨드를 통해 가능했던 조명추가기능을 제거
오브젝트 모드 (기본모드)에서 Shift+A 를 누르면 Add menu가 팝업됨
이 상태에서 Light, Light Probe를 통해 dummy 조명 생성이 가능함
에이블러에서 컨트롤되지않는 조명을 없애기 위해, 이 기능을 UI에서 제거한다.
-

SWTASK-280 Shift+A 커맨드를 통한 조명추가 기능 제거

---

release/scripts/startup/bl_operators/wm.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-287)
- 에이블러 언어 설정을 무시하고 무조건 한글 가이드 링크만 연결되어 있었음
- 현재 에이블러 언어설정 값을 받아 해당 언어의 가이드 링크를 연결
- 영어 + 그 외의 언어는 영문 가이드로 연결

SWTASK 287 조작 튜토리얼 내 가이드 보러가기 언어 오류

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py

전체 선택 (`A`로), delete를 하려고 할 때 backspace키로 안되고 `X` 누르고 안내에 따라 delete 마우스 클릭해야 지워짐.
별도 다른 delete 키가 필요할지?
MacOS에서는 기본적으로 Del 기능을 ⌘ + Backspace 로 실행할 수 있음.
그래서 에이블러에서 오브젝트 삭제에 사용하는 2개의 Del 동작을 Backspace로 변경함
`abler_default.py` 내부 `object.delete` 항목 중 `DEL` 을 사용하는 오브젝트 삭제 단축키는 다음과 같이 두개가 있음
- 기존의 단축키
- `DEL`
- `Shift` + `DEL`
- MacOS용 단축키
- `if params.apple:` 구문 추가
- `Backspace`
- `⌘` + `DEL`
위의 키로 오브젝트가 정상적으로 지워짐.

[SWTASK-289] MacOS에서 Delete 대체 키 적용

---

intern/ghost/GHOST_C-api.h
intern/ghost/intern/GHOST_C-api.cpp
intern/ghost/intern/GHOST_ISystem.cpp
release/scripts/startup/abler/startup_flow.py
source/blender/makesrna/intern/rna_wm_api.c
source/blender/windowmanager/WM_api.h
source/blender/windowmanager/intern/wm_window.c

[이슈](https://carpenstreet.atlassian.net/browse/SWTASK-288?atlOrigin=eyJpIjoiMTJmMTBjYTMwNTNhNDRjYzlmNWY4ZDdhM2ZlMWM5ODEiLCJwIjoiaiJ9)
[QA 이슈](https://carpenstreet.atlassian.net/browse/SW-59?atlOrigin=eyJpIjoiYWJmNDRiMWE2ODQ1NGM1ZGJmN2UzZjNiZTViOTk2MmEiLCJwIjoiaiJ9)
- 더 높은 에이블러 버전에서 저장된  .blend 파일을 열 때, Update ABLER 창이 나오는데, 해당 버튼을 누르면 에러가 발생한다. Sparkle 업데이터에 연결되어야 함.
- `check_sparkle_updater` 함수를 추가하여 bpy 파이썬 모듈에서 쓸 수 있도록 함
- `Acon3dUpdateAblerOperator` 의 `execute` 함수를 os 별로 대응
-  Sparkle 업데이터를 `Acon3dUpdateAblerOperator` 에 연결
- `is_window` -> `is_windows` 변경
- 필요없는 주석 삭제

SWTASK-288 .blend 파일의 버전이 현 프로그램의 버전보다 높을 때 업데이트가 되지 않는 오류

---

release/darwin/README_EULA.txt
release/darwin/abler.applescript
release/darwin/bundle.sh

[Jira 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-320)
[유관 Slack 쓰레드](https://acontainer.slack.com/archives/C02K1NPTV42/p1683594124634229)
- EULA를 DMG에 넣어서 배포해야함
- 한국어와 영문 EULA가 들어있는 `.txt` 파일을 만들어서 `release/darwin` 폴더에 넣음.
- 해당 파일을 `README.txt`로 DMG 내부에 복사해서 넣는 로직을 `bundle.sh`에 추가함

SWTASK-320 DMG에 EULA 넣기

---

release/scripts/startup/abler/lib/version.py

[이슈](https://carpenstreet.atlassian.net/browse/SWTASK-321?atlOrigin=eyJpIjoiZjEzMDk4ZDFhYTlkNGM3Njk1ODQ2ZDZhNWNhZDliYzIiLCJwIjoiaiJ9)
- macOS 에서 현재 로컬의 에이블러 버전을 가져올 수 없음
- get_local_version 함수 내 로직이 너무 많이 실행됨
- python 모듈 plistlib 을 사용하여 info.plist 의 CFBundleVersion을 가져오게 함
- info.plist 의 위치를 찾는 함수 find_info_list 추가
- get_local_version  함수 각 os 별로 리팩토링
- 처음에만 get_local_version 에서 외부 파일을 읽어오는 로직을 수행해서 global 변수에 버전 정보를 저장하고, 그 후에는 저장한 버전 정보를 사용하도록 변경
- get_local_version, get_server_version 함수의 변수 이름 리팩토링

SWTASK-321 에이블러 버전 개선 작업

---

release/darwin/ABLER.app/Contents/Info.plist

[이슈](https://carpenstreet.atlassian.net/browse/SWTASK-313?atlOrigin=eyJpIjoiM2JiNzAxZDE5ZWNjNDg0MWE5MTMzYWJmMWRmNzhmMjgiLCJwIjoiaiJ9)
- 에이블러는 원래 앱 가동 시 / 파일 열기 시에만 업데이트 체크를 하고 있기 떄문에 기본 Sparkle Updater 의 자동 업데이트 및 자동 업데이트 체크를 해제한다.
- info.plist 에 `SUAllowsAutomaticUpdates` 값 false 로 추가하여 체크박스 삭제
- info.plist 에 `SUScheduledCheckInterval`  값 0 로 추가하여 자동 체크 해제

SWTASK-325 Sparkle Updater 자동 체크 해제하기

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/lib/materials/materials_handler.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/pref.py
release/scripts/startup/abler/style_tab/styles_control.py
source/blender/draw/engines/overlay/overlay_engine.c
source/blender/draw/engines/overlay/overlay_extra.c

* 기존 에이블러에서는 싱글톤 태양 광원만 있었고, 이 광원에 대한 프로퍼티 수정만 가능했었음 
* 유저 커스텀 조명에 대한 기능이 필요한 상황
* 유저 커스텀으로 조명을 추가,제거 할 수 있는 기능 개발
* Area, Spot, Point 타입의 조명 지원
* 스타일 탭에서 Lights 패널을 통해서 UI리스트 제공
* UI 리스트에서 각 세부조명에 대한 hide, 프로퍼티 수정(컬러,볼륨,디퓨즈,반사,확산), 조명 삭제 기능 제공
* (블렌더 코드) 조명 UI 트랜스포메이션을 적용하려면 오버레이에서 show_extras 활성화가 필요함, 하지만 이렇게 하면 불필요한 empty object들도 같이 보이기 때문에 영향 최소화를 위해 overlay 코드 수정
* 백그라운드가 제대로 적용되지 않는 상황 => 블렌더 오버레이 로직을 수정하면서 camera overlay 도 OFF 했는데, 해당 부분에서 백그라운드도 관리하고있었음. 따라서 삭제작업을 원복함
* 유저가 delete, X키를 통해 삭제할 시, UI와 실제 오브젝트 리스트 정합성이 안맞는 상황 => depsgraph_update_post 핸들러에 업데이트 함수 추가함 (자주 호출되어서 성능이 염려되어서 필터링 로직 추가함)
* 조명 추가,제거 후 저장,불러오기

SWTASK-86  실내조명 추가,제거,설정 기능

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/general_tab/general.py
release/scripts/startup/bl_ui/space_view3d.py

에이블러 파일 간에 복사, 붙여넣기를 하면 Shadow & Shading 옵션이 붙여넣기한 파일에서 적용되지 않음.
- ~첨부된 파일 chair.blend 를 실행함 (아무 파일이나 상관 없음)~
- 같은 파일 내에서도 해당 오류 발생함
- 오브젝트 선택 후 복사
- 새 에이블러 실행하고 오브젝트 붙여넣기
- Style > Shadow / Shading 옵션을 껐다 켰다하면 발생함
- 임시 방편으로 에이블러 재실행하고 파일 열면 옵션 적용됨
- 오브젝트를 복사하면 구성하는 모든 요소가 복제됨. (재질, 텍스처 이미지, 쉐이더 등)
- 이 때, 블렌더에서는 이미 같은 이름의 데이터가 존재하면 이름을 .001 방식으로 넘버링을함.
- 그래서 `ACON_nodeGroup_combinedToon` 노드 그룹이 복제되면서 `.001` 등의 숫자가 붙게되고, 토글은 원본 쉐이더 노드의 값만 바꾸기 때문에 영향이 없음.
- 구성 요소가 복제되는 부분이 문제점인지? 그렇지 않은지? 에 대해서 간단한 고민 스레드
- [Slack](https://acontainer.slack.com/archives/C02K1NPTV42/p1683801955209529)
- 블렌더의 붙여넣기는 `bpy.ops.view3d.pastebuffer()` 를 사용함.
- 에이블러의 툰 스타일 적용은 `bpy.ops.acon3d.apply_toon_style()` 을 사용함.
- 이 두 기능을 합친 새로운 bpy 오퍼레이터 생성하기
- 오브젝트 붙여넣기와 툰 스타일 적용이 함께되는 오퍼레이터 `class Acon3dPastebuffer` 생성
- …

[SWTASK-326] 오브젝트를 복사하고 붙여넣기를 하면 툰 쉐이더가 복제되면서 Style 탭의 옵션이 적용되지 않는 오류

---

release/scripts/startup/abler/startup_flow.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-327)
- 에러 발생한 with open(path_cookiesFile, "wb") as cookies_file: 코드는 path_cookiesFile 파일이 없으면 자동으로 생성해줌 → 상위 폴더가 없어서 발생하는 에러 같음
- 2.96 폴더를 제거하고 에이블러를 실행시켜주면 2.96 폴더는 자동으로 생성
- 로그인하면 cookies 폴더가 생성되지 않음
- cookies 폴더를 mkdirs 해주는 코드를 추가

[SWTASK-327] macOS에서 로그인 쿠키를 생성하기 전에 접근하는 오류

---

source/blender/blenkernel/intern/undo_system.c

언두를 마구마구 수행해서 에이블러 툰쉐이딩까지 해제해버리는 문제 해결
블렌더 언두는 파이썬이 아닌 C 에서 관리되는 자료구조임 
언두스택에서는 파일전체를 memory에 덤프하고 레퍼런스를 보관하는 식으로 되어있음
따라서 bl_options에 상관없이 모든 오퍼레이션은 언두가 가능함
(bl_options={UNDO}는 단순히 언두스택 체크포인트 추가하는 개념)
언두의 가장 처음에는 original file이 올라가 있음
에이블러 실행후 언두를 계속 수행해서 original file로 돌아가면 툰쉐이딩까지 해제가 됨
해결하기 위해 초기 언두스택에 원본파일을 올리지 않도록 주석처리함
언두스택을 변경하는 것이므로 자동저장이라던가, 다른 기능에 영향이 있을 수 있습니다.
기본적인 기능들에 대해선 한번씩 확인해보았지만, 릴리즈 전에 자세한 테스트가 필요합니다.

초기상태에서 언두 수행시 툰쉐이딩까지 해제되는 현상 해결

---

release/scripts/startup/abler/lib/materials/materials_setup.py

에러 자체는 OS 상관 없이 모두 발생
- 에러 로그
```python
Read prefs: C:\Users\habi\AppData\Roaming\Blender Foundation\Blender\2.96\config\userpref.blend
...생략...
SU | Collection minimized in 10.2803 sec.
Fllowing ACON_mat has invalid format
ACON_mat_clear MI_light_tr_1
SU | Toon-style applied in 10.5104 sec.
SU | Finished importing in 10.5104 sec.
Saved session recovery to 'C:\Users\habi\AppData\Local\Temp\quit.blend'
```
- 재질이 투명 타입이면 `ACON_mat_clear` 가 재질 이름 앞에 붙는데, 스케치업 재질 중 `light` 라는 문자열이 포함된 투명 재질을 가져오면서 전혀 관련 없는 요소를 변형하려는 부분이 문제였음.
- 에이블러 초기 작업 (ABLER 저장소) 코드이며, clear 재질은 따로 처리되고 mirror와 light는 사용되지 않음.
- 해당 코드는 아래 commit > `materials.py`에서 찾을 수 있으며, 불필요한 부분이라 판단하고 삭제함.
- https://github.com/carpenstreet/ABLER/commit/545181d69f1b4251a660c073bb62154cebf7601a

[SWTASK-331] 현재는 사용하지 않는 재질의 포맷을 사용하는 오류

---

release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/scene_tab/layer_control.py

n개의 오브젝트를 선택한 뒤에 특정 단축키 또는 특정 버튼 (또는 컨텍스트 메뉴에 있는 버튼)을 누르면 해당 오브젝트들이 하나의 레이어로 묶여서 하나의 레이어가 추가될 수 있도록 하는 기능
- 생성할 때 팝업
- 레이어 이름 생성
- https://github.com/carpenstreet/blender-translations/pull/56
- Scene 탭의 Layers 패널에 레이어 생성 버튼 추가
- Collection을 생성하면서 선택된 오브젝트를 collection에 연결
- 오브젝트가 선택되지 않으면 비활성 하기
- Collection을 추가하면 Layers 목록에 새 collection 업데이트 하기
- [Notion: 블렌더 to 에이블러 수동 편집](https://www.notion.so/acon3d/to-127d21725cc641b1a28d6451d3949bb1?pvs=4)
- 위 문서의 레이어 생성 방법 참고
- 레이어 이름 입력을 위해서 실행 시 dialog를 발생하도록 변경
- Collection index 탐색을 이름 연결 방식으로 변경
- Blender의 컬렉션 데이터는 이름순으로 정렬되기 때문에 `collection_index` 값이 달라짐
- 컬렉션을 이름 기반으로 생성하고 오브젝트를 직접 연결하는 방식을 사용
- [Where to find collection_index for moving an object?](https://devtalk.blender.org/t/where-to-find-collection-index-for-moving-an-object/3289)
- …

[SWTASK-132] 레이어 추가 기능

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/pref.py

[티켓](https://carpenstreet.atlassian.net/browse/SWTASK-359?atlOrigin=eyJpIjoiNDE1MjI1NDBiMTZlNDBiM2E1MGNlOTMzOWNiNTIxMjQiLCJwIjoiaiJ9)
- 고품질 렌더 중간에 `_HQ_` 넣기
- 오려내기 렌더
- 오려내기 대상 - `_snipped_objects`
- 전체 - `_snipped_full`
- 빠른 렌더 - `_quick`
- Acon3dRenderDirOperator 를 상속하도록 변경
- 폴더 명에 씬 추가하는 작업 제거
- 디폴트 폴더의 이름을 프로젝트 이름으로 하고, 없다면 씬 이름으로 하도록 변경함
- 첫 렌더 후에는 render_default_path 에 선택한 폴더명을 저장하여 같은 프로젝트에서는 렌더 대상 파일을 열 때 항상 같은 폴더를 열도록 수정
- 빠른 렌더, 스닙 렌더도 렌더 타입으로 추가하여 Render Queue 에 넘겨줌
- 그에 따라 많아진 렌더 타입 관리 및 상수화를 위해 Enum RenderType 생성
- Render Queue 의 원소로 들어가는 Tuple의 순서를 (Scene Name, Scene, Render Type) => (Scene, Render Type, Scene Name) 로 변경
- Scene, Render Type 이 항상 들어가고, Scene Name은 Optional 하기 때문
- prepare_queue - 추상 메서드로 변경하여 상속받은 클래스에서 무조건 구현하도록 함
- 주석 추가
- 명확한 의미를 위해 qitem 으로 사용하던 부분을 …

SWTASK-359 에이블러 렌더 이미지 저장 정책을 폴더링 방식에서 파일명 방식으로 변경

---

release/scripts/startup/bl_operators/wm.py

스플래쉬 창의  회원가입, 사용법 안내, 공지사항 등의 UX를 강화하기 위한 작업
1. 언어를 변경해도 적용안되던 공지사항, 해쉬맵(언어->내용) 으로 관리하도록 수정해서 개선
2. 회원가입 버튼의 위치 로그인창 아래로 옮겨서 UX 개선
3. 중요도에 맞게 공지사항 리스트 위치 수정
before
after

[SWTASK-356] 에이블러 스플래쉬 UX 개선 작업

---

release/darwin/ABLER.app/Contents/Info.plist

[티켓](https://carpenstreet.atlassian.net/browse/SWTASK-419?atlOrigin=eyJpIjoiMjdiODU1MzJmYTE5NDk3MWE0NjFjZTE3NDc4YTFiNWUiLCJwIjoiaiJ9)
- macOS 시스템 및 스파클의 일본어 지원을 위해 info.plist 를 수정하였습니다.

SWTASK-419 macOS 시스템 일본어 지원 추가

---

release/scripts/startup/abler/pref.py
source/blender/blenkernel/BKE_undo_system.h
source/blender/blenkernel/intern/undo_system.c
source/blender/makesrna/intern/rna_wm_api.c
source/blender/windowmanager/intern/wm_files.c

언두스택 초기원소 제거작업의 사이드이펙트를 막기위한 작업
발견된 사례로는, 실행후 가만히 있으면 오토세이브 로직 작동시마다 언두스택이 비어서 warning이 발생함. 
(기존 블렌더 로직은 오토세이브마다 언두스택 가장 위의 메모리덤프를 내려버리는데, 스택이 비어있을리 없어서 심각한 상황으로 판단해서 경고한것)
* 기존의 언두스택 로직 복구
* 초기 로딩시, 툰쉐이딩이 적용된 코니룸을 undo_stack에 넣어주는 로직 추가

SWTASK-427 툰쉐이딩이 된 코니룸으로 UndoStack 초기화하도록 작업

---

release/scripts/startup/abler/pref.py
source/blender/editors/interface/interface.c

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-416)
- [번역 누락 추가](https://github.com/carpenstreet/blender-translations/pull/60) 를 위한 에이블러 코드 수정
- 블랜더에서 저장한 파일 오픈시 에러 구문 번역을 위한 `text_ctxt="abler"` 추가
- 파일 브라우저 헤더에서 번역 안되는 에러
- 블렌더 3.2.2 버전에선 번역 안되고 3.3.0 버전에서 번역이 되므로 그 사이 commit 내용들 비교해서 에러 해결 코드 추가
- https://archive.blender.org/developer/D15417 참조

SWTASK-416 일문 번역 관련 검수 내용 반영

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/style_tab/styles_control.py

조명기능에서 diffuse(난반사), specular(반사), volume(볼륨 : 불, 안개 같은 물체뚫는 정도)
가 에이블러 툰쉐이더에서 사실상 효과가 거의 없음
난반사만 디폴트값을 설정해주고, 색상과 에너지만으로 컨트롤 하도록 사용성을 개선함.
1. 난반사 디폴트값 수정 
2. 난반사, 반사, 볼륨 필드 제거

조명기능 사용성 개선

---

release/scripts/startup/abler/export_tab/render_control.py

[티켓](https://carpenstreet.atlassian.net/jira/software/c/projects/SWTASK/boards/22?modal=detail&selectedIssue=SWTASK-485&assignee=63c78e769d59ec705fec7f44)
- 퀵렌더를 2번 이상 실행하는 경우, 기존 이미지를 덮어씌우면서 같은 이미지가 두 장 생성되는 오류가 발생함
- modal 함수 내에서 quick 렌더만 별개로 분기처리하여 render.opengl, pre_render, post_render 함수를 실행시켜줌
- 위 방법이 비효율적이라 리팩토링 시 핸들러를 사용하는 렌더와 사용하지 않는 렌더를 나누는 것이 좋아보임

SWTASK-485 퀵 렌더 2번 이상 실행 시 이미지를 덮어쓰는 오류

---

release/scripts/startup/abler/lib/scenes.py

씬을 새로 생성할 시에, light_index가 초기화 되지 않던 문제 수정
인덱스로 조명에 접근할때에 방어로직 추가

SWTASK-521 조명기능 인덱스 관련 에러 수정 및 안정화

---

release/scripts/startup/abler/pref.py
release/scripts/startup/bl_ui/space_toolsystem_toolbar.py

3D 커서 지원작업 - 1
아래의 사진을 참고 
* 3D커서 툴 아이콘 복구
* 3D 커서를 뷰포트에 표시

3D 커서 아이콘 복구 및 뷰포트에 표시

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/layers.py

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-475)
- 레이어 토글 속도 개선 작업
- hide_set()으로 설정하는거 외에 당장은 좋은 방법이 없어(카드 참고) 일차적으로 개선
- obj.hide_set으로 변경

[SWTASK-475] 레이어 토글 속도 개선

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/style_tab/styles_control.py

1. 아이콘 토글을 이용해서 3D 커서 좌표에 조명 생성하는 기능 추가
(만약 토글 해제 되어 있다면, 월드좌표계 원점에 생성됨)
2. 조명생성 오퍼레이션 언두 지원

3D 커서 기반의 조명 생성 기능 추가

---

release/scripts/startup/abler/lib/render.py

[티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-477?atlOrigin=eyJpIjoiYjY5OGE1YTM0YzExNDcxYjljYTNiYWUyZjQ0OWFlMGMiLCJwIjoiaiJ9)
- 오브젝트 숨기기(H) 후 렌더를 한 후, 숨기기를 해제(alt+H)한 후 다시 렌더를 하면 오브젝트 누락이 발생함
hide_render 를 true 로 바꿔주는 함수는 있지만 false 로 바꿔주는 함수는 없다.
- visibility 를 변경하는 메서드를 항상 hide_set 으로 고정하고, (hide_viewport 를 사용하지 않고) 렌더 직전에 match_object_visibility 함수에서 hide_render 에 hide_get() 값을 준다.
- 최신 develop 으로 io_skp 모듈 업데이트
아웃라이너의 카메라 on/off 의 값이 렌더 결과물과 다를 수 있음.

SWTASK-477 오브젝트 표시 단축키를 사용했을 때 렌더러에서 숨겨져 있어 렌더가 되지 않는 오류

---

release/scripts/startup/abler/export_tab/render_control.py
release/scripts/startup/abler/style_tab/styles_control.py

퀵렌더시 발생하는 가이드라인 노출 현상을 수정함
* 렌더작업이 async로 이루어져 가이드라인 토글해야하는 정확한 타이밍 설정이 어려운 것을 확인함
* post_render 핸들러에 토글 작업을 추가함
* 기타 간단한 조명삭제기능 방어로직 추가

SWTASK-580 퀵렌더시 가이드라인이 보이는 현상 수정
